"""Readings for the minihongo-speak deck that legitimately differ from UniDic.
Consumed by scripts/check_pronunciation.py (surface -> correct reading).

Every reading here is minihongo's own, copied from its CSVs by
scripts/import_minihongo_speak.py rather than authored in this repo. What the
list whitelists is UniDic answering out of context, in two shapes:

  * minihongo paraphrases with the 231 core words, so a kanji almost always
    stands alone as its native reading where UniDic expects a compound: 言【い】う
    comes back げん, 多【おお】い さわ, 起【お】こる き, 一【ひと】つ いち.
  * minihongo's own conventions: 時 is とき and 日 is にち wherever they mean
    "a time" and "a day", where UniDic reads the bare characters じ and ひ.

Keys are whole words, never bare kanji that a longer word contains - a key of
言 would cut 言葉 into 言 + 葉 and read it いは. Where a surface is read two ways
in the deck the key carries the okurigana that tells them apart (来る / 来た,
出る / 出す), and the longer key wins because check_pronunciation splits
longest-first.

Regenerate the deck with scripts/import_minihongo_speak.py and this file should
still bring `check_pronunciation.py --deck minihongo-speak` to zero. A new
mismatch means minihongo changed a reading; read it before whitelisting it.
"""

ACCEPTED = {
    '一つくだ': 'ひとつくだ',
    '一つだけ': 'ひとつだけ',
    '一つにし': 'ひとつにし',
    '一つにす': 'ひとつにす',
    '一りしか': 'ひとりしか',
    '三百五十': 'さんびゃくごじゅう',
    '入ります': 'はいります',
    '口にある': 'ぐちにある',
    '日からで': 'にちからで',
    '日にしま': 'にちにしま',
    '日のまと': 'にちのまと',
    '日ほんで': 'にほんで',
    '一つく': 'ひとつく',
    '一つだ': 'ひとつだ',
    '一つに': 'ひとつに',
    '一つの': 'ひとつの',
    '一りし': 'ひとりし',
    '一りで': 'ひとりで',
    '二百円': 'にひゃくえん',
    '入りま': 'はいりま',
    '十分前': 'じゅうぷんまえ',
    '口にあ': 'ぐちにあ',
    '日から': 'にちから',
    '日です': 'にちです',
    '日とお': 'にちとお',
    '日にし': 'にちにし',
    '日のま': 'にちのま',
    '日ほん': 'にほん',
    '書き方': 'かきかた',
    '来たり': 'くたり',
    '来ない': 'こない',
    '毎日書': 'まいにちか',
    '一つ': 'ひとつ',
    '一り': 'ひとり',
    '二十': 'にじゅう',
    '二本': 'にほん',
    '今日': 'いまにち',
    '何人': 'なんにん',
    '動物': 'どうぶつ',
    '変わ': 'かわ',
    '日か': 'にちか',
    '日で': 'にちで',
    '日と': 'にちと',
    '日に': 'にちに',
    '日の': 'にちの',
    '日は': 'にちは',
    '日ほ': 'にほ',
    '来な': 'こな',
    '言葉': 'ことば',
    '三': 'みっ',
    '与': 'あた',
    '二': 'ふた',
    '会': 'あ',
    '何': 'なに',
    '作': 'つく',
    '使': 'つか',
    '分': 'わ',
    '切': 'き',
    '助': 'たす',
    '動': 'うご',
    '同': 'おな',
    '多': 'おお',
    '好': 'す',
    '始': 'はじ',
    '守': 'まも',
    '寒': 'さむ',
    '小': 'ちい',
    '少': 'すこ',
    '年': 'とし',
    '座': 'すわ',
    '強': 'つよ',
    '待': 'ま',
    '怒': 'おこ',
    '思': 'おも',
    '悲': 'かな',
    '戦': 'たたか',
    '持': 'も',
    '探': 'さが',
    '教': 'おし',
    '新': 'あたら',
    '日': 'にち',
    '明': 'あす',
    '時': 'とき',
    '暑': 'あつ',
    '書': 'か',
    '楽': 'たの',
    '欲': 'ほ',
    '止': 'と',
    '歩': 'ある',
    '生': 'い',
    '知': 'し',
    '私': 'わたし',
    '笑': 'わら',
    '終': 'お',
    '考': 'かんが',
    '聞': 'き',
    '良': 'よ',
    '行': 'い',
    '言': 'い',
    '読': 'よ',
    '買': 'か',
    '起': 'お',
    '近': 'ちか',
    '速': 'はや',
    '違': 'ちが',
    '選': 'えら',
    '重': 'おも',
    '金': 'かね',
    '閉': 'し',
    '開': 'あ',
    '願': 'ねが',
    '食': 'た',
    '飲': 'の',
    '高': 'たか',
}
