"""The committed uv.lock must keep the format markers an old uv strips.

`required-version` in pyproject.toml only binds uv 0.5.14 and later, which is
where that setting was introduced. An older uv discards the whole `[tool.uv]`
table with a parse warning and rewrites the lock anyway. These tests read the
file instead of asking uv, so they catch the downgrade whatever produced it.
"""

import tomllib
from pathlib import Path

import pytest

LOCK_PATH = Path(__file__).parent.parent / "uv.lock"

DOWNGRADE_HINT = (
    "uv.lock was regenerated by a uv older than the required-version floor in "
    "pyproject.toml. Restore the lock from master; a pinned-revision bump edits "
    "the revision strings in uv.lock by hand, it never regenerates the file. "
    "Verify with `uv sync --frozen`."
)


@pytest.fixture(scope="module")
def lock():
    return tomllib.loads(LOCK_PATH.read_text())


def test_revision_is_at_least_3(lock):
    """>= 3, not == 3: a newer uv may legitimately raise the revision, and that
    is not the downgrade this guards against. Do not tighten to equality."""
    assert "revision" in lock, DOWNGRADE_HINT
    assert lock["revision"] >= 3, DOWNGRADE_HINT


def test_registry_packages_carry_upload_time(lock):
    """Every sdist and wheel entry of a registry package carries it. The
    git-pinned jpanki and the virtual root package have no PyPI upload timestamp
    to record, so they are excluded; `anki` ships wheels only and three packages
    ship an sdist only, hence the per-entry rather than per-package check."""
    missing = [
        package["name"]
        for package in lock["package"]
        if "registry" in package["source"]
        and any("upload-time" not in entry for entry in _artifacts(package))
    ]
    assert not missing, f"{DOWNGRADE_HINT} Packages missing upload-time: {missing}"


def _artifacts(package):
    sdist = package.get("sdist")
    return ([sdist] if sdist else []) + package.get("wheels", [])
