name: Bug Report
description: Report an issue with audio generation, deck creation, or scripts
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command...
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: dropdown
    id: script
    attributes:
      label: Which script?
      options:
        - generate_audio.py
        - create_deck.py
        - validate.py
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "3.13.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 24.04 / macOS 15 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Paste any error messages
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched for existing issues
          required: true
        - label: I have espeak-ng installed
          required: true
        - label: I ran `uv sync` to install dependencies
          required: true
