[deck]
slug = "it-kundoku"
name = "IT Kundoku"
model_id = 1708493424
deck_base_id = 2160501211

[tiers]
count = 3

[tiers.names]
1 = "Tier 01 - Grammar"
2 = "Tier 02 - Actions"
3 = "Tier 03 - Nouns, Descriptors & Patterns"

[tiers.sizes]
1 = 27
2 = 24
3 = 38
