#!/usr/bin/env python3
"""Add KeyMeaning column to vocabulary CSVs.

Translates the Cloze (key vocabulary) field to English.
"""

import csv
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent

# Comprehensive IT vocabulary translations
TRANSLATIONS = {
    # Status & Progress
    '完了': 'completed',
    '取り組んで': 'working on',
    'ブロック': 'blocked',
    '更新': 'update',
    '問題': 'problem/issue',
    '修正': 'fix',
    '確認': 'confirm/check',
    '準備': 'preparation',
    '必要': 'necessary/need',
    '手伝って': 'help',
    '質問': 'question',
    'ありがとう': 'thank you',
    'いいですね': 'sounds good',
    'なるほど': 'I see',
    '了解': 'understood',
    'もちろん': 'of course',
    'すみません': 'sorry/excuse me',
    '実は': 'actually',
    'おそらく': 'probably',
    'かもしれません': 'might/maybe',
    '確実に': 'definitely',
    '基本的に': 'basically',
    '現在': 'currently',
    'まだ': 'still/not yet',
    'すでに': 'already',
    '終わって': 'finished',
    'すぐに': 'immediately/soon',
    '後で': 'later',
    '今すぐ': 'right now',
    '今日中': 'by today',
    '明日まで': 'by tomorrow',
    '週末まで': 'by the weekend',
    '来週': 'next week',
    '先週': 'last week',
    '昨日': 'yesterday',
    '今朝': 'this morning',
    '午後': 'afternoon',
    '昼食前': 'before lunch',
    '昼食後': 'after lunch',
    '会議中': 'during the meeting',
    '会議後': 'after the meeting',
    '終業前': 'before end of work',

    # Common Expressions
    '1対1': 'one-on-one',
    'あれば良い': 'nice to have',
    'お知らせ': 'heads up/notice',
    'きれい': 'clean/nice',
    'これは意味する': 'this means',
    'ちなみに': 'by the way',
    'できるだけ早く': 'ASAP',
    'また話しましょう': 'let\'s circle back',
    'まとめ': 'summary',
    'やり方': 'approach/way',
    'アクションアイテム': 'action item',
    'アジェンダ': 'agenda',
    'アプローチ': 'approach',
    'アーキテクチャ': 'architecture',
    'アーティファクト': 'artifact',
    'イシュー': 'issue',
    'オフライン': 'offline',
    'オンライン': 'online',
    'カバー': 'cover',
    'キャッチアップ': 'catch up',
    'クリア': 'clear',
    'サポート': 'support',
    'シェア': 'share',
    'ジュニア': 'junior',
    'シニア': 'senior',
    'スキップ': 'skip',
    'ステータス': 'status',
    'スムーズ': 'smooth',
    'タイムライン': 'timeline',
    'チェック': 'check',
    'ディスカッション': 'discussion',
    'ドキュメンテーション': 'documentation',
    'ノート': 'note',
    'ハイライト': 'highlight',
    'バックアップ': 'backup',
    'ピック': 'pick',
    'フィードバック': 'feedback',
    'フォロー': 'follow up',
    'フォローアップ': 'follow up',
    'ブリーフィング': 'briefing',
    'プレゼン': 'presentation',
    'ブロッカー': 'blocker',
    'ベース': 'base',
    'ペンディング': 'pending',
    'ボトルネック': 'bottleneck',
    'マージ': 'merge',
    'ミス': 'mistake',
    'メンション': 'mention',
    'リマインダー': 'reminder',
    'レビュアー': 'reviewer',
    'ワークフロー': 'workflow',
    '一緒に': 'together',
    '今週': 'this week',
    '代わりに': 'instead',
    '以前': 'before/previously',
    '例えば': 'for example',
    '再度': 'again',
    '別の': 'another',
    '前に': 'before',
    '参加': 'join/participate',
    '同じ': 'same',
    '困っている': 'having trouble',
    '大丈夫': 'OK/fine',
    '少し': 'a little',
    '心配': 'worry',
    '感謝': 'appreciate',
    '懸念': 'concern',
    '把握': 'grasp/understand',
    '提出': 'submit',
    '新しい': 'new',
    '最初': 'first',
    '最後': 'last',
    '次': 'next',
    '残り': 'remaining',
    '直接': 'directly',
    '簡単': 'simple/easy',
    '終了': 'end/finish',
    '見つけ': 'find',
    '見直し': 'review again',
    '話し合い': 'discussion',
    '詳細': 'details',
    '近い': 'close/near',
    '違う': 'different',
    '適切': 'appropriate',
    '重要': 'important',

    # IT Specific Japanese
    'API設計': 'API design',
    'E2Eテスト': 'E2E test',
    'IPアドレス': 'IP address',
    'NATゲートウェイ': 'NAT gateway',
    'nullチェック': 'null check',
    'アクセシビリティ': 'accessibility',
    'アクセス制御': 'access control',
    'アサーション': 'assertion',
    'アップタイム': 'uptime',
    'アニメーション': 'animation',
    'アベイラビリティゾーン': 'availability zone',
    'アラート': 'alert',
    'アラーム': 'alarm',
    'アンマウント': 'unmount',
    'イベント': 'event',
    'イベントドリブン': 'event-driven',
    'インシデント': 'incident',
    'インスタンス': 'instance',
    'インターフェース': 'interface',
    'インフラ': 'infrastructure',
    'ウェブフック': 'webhook',
    'エスカレーション': 'escalation',
    'エッジケース': 'edge case',
    'エラーハンドリング': 'error handling',
    'エンコーディング': 'encoding',
    'オートスケーリング': 'auto-scaling',
    'オブザーバビリティ': 'observability',
    'オンコール': 'on-call',
    'カスタマイズ': 'customize',
    'カナリアリリース': 'canary release',
    'キャパシティ': 'capacity',
    'クエリパラメータ': 'query parameter',
    'クラウドネイティブ': 'cloud native',
    'クレデンシャル': 'credentials',
    'グローバル変数': 'global variable',
    'コスト': 'cost',
    'コネクションプール': 'connection pool',
    'コンカレンシー': 'concurrency',
    'コンフィグ': 'config',
    'コンプライアンス': 'compliance',
    'コードカバレッジ': 'code coverage',
    'サブスクリプション': 'subscription',
    'サーキットブレーカー': 'circuit breaker',
    'シークレット': 'secret',
    'シャーディング': 'sharding',
    'ジョブ': 'job',
    'スケジューラー': 'scheduler',
    'スケジュール': 'schedule',
    'スコープ': 'scope',
    'スタック': 'stack',
    'スタックトレース': 'stack trace',
    'ステートレス': 'stateless',
    'ステートフル': 'stateful',
    'ストリーミング': 'streaming',
    'スナップショット': 'snapshot',
    'スパイク': 'spike',
    'スプリントレビュー': 'sprint review',
    'スレッドセーフ': 'thread-safe',
    'セキュリティパッチ': 'security patch',
    'セキュリティグループ': 'security group',
    'ソースコード': 'source code',
    'タイプセーフ': 'type-safe',
    'ダウンタイム': 'downtime',
    'チューニング': 'tuning',
    'ツール': 'tool',
    'ディペンデンシー': 'dependency',
    'ディレクトリ': 'directory',
    'デグレ': 'regression',
    'デシリアライズ': 'deserialize',
    'デッドコード': 'dead code',
    'デバッガー': 'debugger',
    'デフォルト': 'default',
    'デプロイメント': 'deployment',
    'トラブルシューティング': 'troubleshooting',
    'トランスパイル': 'transpile',
    'トリガー': 'trigger',
    'トレードオフ': 'trade-off',
    'ネームスペース': 'namespace',
    'ハンドラ': 'handler',
    'ハードコーディング': 'hardcoding',
    'バグトラッキング': 'bug tracking',
    'バックエンド': 'backend',
    'バッファ': 'buffer',
    'バリデーション': 'validation',
    'パイプライン': 'pipeline',
    'パフォーマンスチューニング': 'performance tuning',
    'パラメータ': 'parameter',
    'パース': 'parse',
    'ビジネスロジック': 'business logic',
    'ビルドパイプライン': 'build pipeline',
    'ファイル': 'file',
    'フェッチ': 'fetch',
    'フォーマット': 'format',
    'フォールバック': 'fallback',
    'フラグ': 'flag',
    'フロントエンド': 'frontend',
    'ブルーグリーンデプロイ': 'blue-green deploy',
    'プリフェッチ': 'prefetch',
    'プルリクエスト': 'pull request',
    'プロキシ': 'proxy',
    'プロダクション': 'production',
    'プロビジョニング': 'provisioning',
    'ヘルスチェック': 'health check',
    'ベストプラクティス': 'best practice',
    'ホスティング': 'hosting',
    'ホットリロード': 'hot reload',
    'ボイラープレート': 'boilerplate',
    'ポストモーテム': 'postmortem',
    'ポーリング': 'polling',
    'マイグレーション': 'migration',
    'マスターブランチ': 'master branch',
    'メインブランチ': 'main branch',
    'メソッドチェーン': 'method chain',
    'メトリクス': 'metrics',
    'メモリリーク': 'memory leak',
    'メンテナンス': 'maintenance',
    'モジュール': 'module',
    'モニタリング': 'monitoring',
    'ユースケース': 'use case',
    'ライフサイクル': 'lifecycle',
    'ランタイム': 'runtime',
    'リクエストボディ': 'request body',
    'リスナー': 'listener',
    'リソース': 'resource',
    'リファレンス': 'reference',
    'リポジトリ': 'repository',
    'リモート': 'remote',
    'リライト': 'rewrite',
    'リリースノート': 'release notes',
    'レイテンシー': 'latency',
    'レガシー': 'legacy',
    'レジストリ': 'registry',
    'レスポンスタイム': 'response time',
    'レプリケーション': 'replication',
    'ロギング': 'logging',
    'ロジック': 'logic',
    'ロードテスト': 'load test',
    'ローリングアップデート': 'rolling update',
    'ローンチ': 'launch',
    'ワーカー': 'worker',
    '互換': 'compatible',
    '冪等': 'idempotent',
    '分散': 'distributed',
    '可観測性': 'observability',
    '呼び出し': 'call/invoke',
    '圧縮': 'compress',
    '型定義': 'type definition',
    '外部キー': 'foreign key',
    '宣言的': 'declarative',
    '並行処理': 'concurrency',
    '並列処理': 'parallel processing',
    '主キー': 'primary key',
    '具体的に': 'specifically',
    '再現': 'reproduce',
    '再試行': 'retry',
    '切り戻し': 'rollback',
    '制限': 'limit/restriction',
    '動的': 'dynamic',
    '同期処理': 'synchronous',
    '命名規則': 'naming convention',
    '変換': 'convert',
    '多分': 'maybe/probably',
    '安定': 'stable',
    '定義': 'definition',
    '実行時': 'runtime',
    '容量': 'capacity',
    '密結合': 'tight coupling',
    '展開': 'deploy/expand',
    '属性': 'attribute',
    '引数': 'argument',
    '影響範囲': 'impact scope',
    '復旧': 'recovery',
    '推奨': 'recommended',
    '接続': 'connection',
    '整合性': 'consistency',
    '最小権限': 'least privilege',
    '本番環境': 'production env',
    '構造': 'structure',
    '権限昇格': 'privilege escalation',
    '権限設定': 'permission settings',
    '永続化': 'persistence',
    '疎結合': 'loose coupling',
    '直す': 'fix',
    '破壊的変更': 'breaking change',
    '秘密鍵': 'private key',
    '移行': 'migrate',
    '競合': 'conflict',
    '自動化': 'automation',
    '複製': 'duplicate/clone',
    '解析': 'parse/analyze',
    '設定ファイル': 'config file',
    '認証情報': 'credentials',
    '試す': 'try',
    '読み取り専用': 'read-only',
    '調整': 'adjust/coordinate',
    '起きて': 'happening',
    '軽量': 'lightweight',
    '返り値': 'return value',
    '追跡': 'track',
    '通る': 'pass',
    '通知': 'notification',
    '連携': 'integrate',
    '遅い': 'slow',
    '運用': 'operations',
    '過去': 'past',
    '違い': 'difference',
    '適用': 'apply',
    '静的': 'static',
    '順番': 'order',
    '高負荷': 'high load',

    # Communication
    '共有': 'share',
    '連絡': 'contact',
    '報告': 'report',
    '説明': 'explain',
    '相談': 'consult',
    '議論': 'discuss',
    '提案': 'propose/suggest',
    '依頼': 'request',
    '承認': 'approve',
    '却下': 'reject',
    '保留': 'on hold',
    '延期': 'postpone',
    '優先': 'prioritize',
    '対応': 'handle/respond',
    '検討': 'consider',
    '調査': 'investigate',
    '分析': 'analyze',
    '評価': 'evaluate',
    '見積もり': 'estimate',
    '計画': 'plan',
    '設計': 'design',
    '実装': 'implement',
    '開発': 'develop',
    'テスト': 'test',
    'デプロイ': 'deploy',
    'リリース': 'release',
    'ロールバック': 'rollback',
    'マージ': 'merge',
    'プッシュ': 'push',
    'プル': 'pull',
    'コミット': 'commit',
    'ブランチ': 'branch',
    'フォーク': 'fork',
    'クローン': 'clone',

    # Development Terms
    'バグ': 'bug',
    'エラー': 'error',
    '例外': 'exception',
    'クラッシュ': 'crash',
    'フリーズ': 'freeze',
    'タイムアウト': 'timeout',
    'リトライ': 'retry',
    'キャッシュ': 'cache',
    'ログ': 'log',
    'デバッグ': 'debug',
    'トレース': 'trace',
    'プロファイル': 'profile',
    '最適化': 'optimize',
    'リファクタリング': 'refactoring',
    'リファクタ': 'refactor',
    'コードレビュー': 'code review',
    'レビュー': 'review',
    'フィードバック': 'feedback',
    'コメント': 'comment',
    'ドキュメント': 'documentation',
    '仕様': 'specification',
    '要件': 'requirement',
    '機能': 'feature/function',
    'モジュール': 'module',
    'コンポーネント': 'component',
    'ライブラリ': 'library',
    'フレームワーク': 'framework',
    'パッケージ': 'package',
    '依存関係': 'dependency',
    'バージョン': 'version',
    'アップグレード': 'upgrade',
    'ダウングレード': 'downgrade',
    '互換性': 'compatibility',
    '非推奨': 'deprecated',
    '廃止': 'obsolete',

    # Technical Concepts
    '認証': 'authentication',
    '認可': 'authorization',
    '暗号化': 'encryption',
    '復号': 'decryption',
    'ハッシュ': 'hash',
    'トークン': 'token',
    'セッション': 'session',
    'クッキー': 'cookie',
    'ヘッダー': 'header',
    'ボディ': 'body',
    'パラメータ': 'parameter',
    'クエリ': 'query',
    'レスポンス': 'response',
    'リクエスト': 'request',
    'エンドポイント': 'endpoint',
    'ルート': 'route',
    'パス': 'path',
    'ミドルウェア': 'middleware',
    'コントローラー': 'controller',
    'サービス': 'service',
    'リポジトリ': 'repository',
    'モデル': 'model',
    'スキーマ': 'schema',
    'マイグレーション': 'migration',
    'シード': 'seed',
    'インデックス': 'index',
    '制約': 'constraint',
    'トランザクション': 'transaction',
    'ロック': 'lock',
    'デッドロック': 'deadlock',
    '同期': 'sync',
    '非同期': 'async',
    'コールバック': 'callback',
    'プロミス': 'promise',
    'イベント': 'event',
    'リスナー': 'listener',
    'ハンドラー': 'handler',
    'フック': 'hook',

    # Infrastructure
    'サーバー': 'server',
    'クライアント': 'client',
    'データベース': 'database',
    'ストレージ': 'storage',
    'ネットワーク': 'network',
    'ロードバランサー': 'load balancer',
    'プロキシ': 'proxy',
    'ゲートウェイ': 'gateway',
    'ファイアウォール': 'firewall',
    'コンテナ': 'container',
    'オーケストレーション': 'orchestration',
    'クラスター': 'cluster',
    'ノード': 'node',
    'ポッド': 'pod',
    'レプリカ': 'replica',
    'スケール': 'scale',
    'スケーリング': 'scaling',
    'オートスケール': 'autoscale',
    'フェイルオーバー': 'failover',
    '冗長性': 'redundancy',
    '可用性': 'availability',
    '信頼性': 'reliability',
    'パフォーマンス': 'performance',
    'レイテンシ': 'latency',
    'スループット': 'throughput',
    '帯域幅': 'bandwidth',

    # Monitoring & Logging
    'メトリクス': 'metrics',
    'アラート': 'alert',
    '通知': 'notification',
    'ダッシュボード': 'dashboard',
    '可視化': 'visualization',
    '監視': 'monitoring',
    'ヘルスチェック': 'health check',
    'ステータス': 'status',
    '状態': 'state',

    # Security
    '脆弱性': 'vulnerability',
    '攻撃': 'attack',
    '侵入': 'intrusion',
    '漏洩': 'leak',
    '権限': 'permission',
    'ロール': 'role',
    'ポリシー': 'policy',
    '監査': 'audit',
    'コンプライアンス': 'compliance',

    # Meetings & Collaboration
    '打ち合わせ': 'meeting',
    'ミーティング': 'meeting',
    'スタンドアップ': 'standup',
    'スプリント': 'sprint',
    'レトロ': 'retro',
    'プランニング': 'planning',
    'バックログ': 'backlog',
    'チケット': 'ticket',
    'タスク': 'task',
    'ストーリー': 'story',
    'エピック': 'epic',
    'マイルストーン': 'milestone',
    'デッドライン': 'deadline',
    '締め切り': 'deadline',
    '期限': 'due date',
    '進捗': 'progress',
    '遅延': 'delay',
    '前倒し': 'ahead of schedule',

    # Actions
    '作成': 'create',
    '削除': 'delete',
    '変更': 'change/modify',
    '追加': 'add',
    '編集': 'edit',
    '保存': 'save',
    '読み込み': 'load',
    '書き込み': 'write',
    '送信': 'send',
    '受信': 'receive',
    'アップロード': 'upload',
    'ダウンロード': 'download',
    'インポート': 'import',
    'エクスポート': 'export',
    '実行': 'execute/run',
    '停止': 'stop',
    '再起動': 'restart',
    '起動': 'start',
    '初期化': 'initialize',
    '設定': 'configure/settings',
    '構成': 'configuration',
    '有効': 'enable',
    '無効': 'disable',
    '切り替え': 'switch/toggle',
    '選択': 'select',
    '検索': 'search',
    'フィルター': 'filter',
    'ソート': 'sort',
    'ページング': 'pagination',

    # Code Quality
    'リント': 'lint',
    'フォーマット': 'format',
    '型チェック': 'type check',
    'ユニットテスト': 'unit test',
    '統合テスト': 'integration test',
    'E2Eテスト': 'E2E test',
    'カバレッジ': 'coverage',
    'アサーション': 'assertion',
    'モック': 'mock',
    'スタブ': 'stub',
    'フィクスチャ': 'fixture',

    # Data
    '配列': 'array',
    'オブジェクト': 'object',
    '文字列': 'string',
    '数値': 'number',
    '真偽値': 'boolean',
    'null': 'null',
    '未定義': 'undefined',
    '型': 'type',
    'インターフェース': 'interface',
    'クラス': 'class',
    '関数': 'function',
    'メソッド': 'method',
    'プロパティ': 'property',
    '変数': 'variable',
    '定数': 'constant',
    '引数': 'argument',
    '戻り値': 'return value',

    # UI/UX
    'ボタン': 'button',
    'フォーム': 'form',
    '入力': 'input',
    '出力': 'output',
    '表示': 'display',
    '非表示': 'hide',
    'モーダル': 'modal',
    'ポップアップ': 'popup',
    'ツールチップ': 'tooltip',
    'ドロップダウン': 'dropdown',
    'タブ': 'tab',
    'ナビゲーション': 'navigation',
    'サイドバー': 'sidebar',
    'ヘッダー': 'header',
    'フッター': 'footer',
    'レイアウト': 'layout',
    'レスポンシブ': 'responsive',
    'アクセシビリティ': 'accessibility',

    # Common Phrases
    '〜してください': 'please do~',
    '〜できます': 'can do~',
    '〜しましょう': 'let\'s do~',
    '〜したい': 'want to~',
    '〜と思います': 'I think~',
    '〜かな': 'I wonder~',
    '〜ですね': 'isn\'t it~',
    '〜みたい': 'seems like~',

    # Tech Terms (English)
    'API': 'API',
    'REST': 'REST',
    'GraphQL': 'GraphQL',
    'SQL': 'SQL',
    'JSON': 'JSON',
    'XML': 'XML',
    'YAML': 'YAML',
    'CSV': 'CSV',
    'HTML': 'HTML',
    'CSS': 'CSS',
    'JavaScript': 'JavaScript',
    'TypeScript': 'TypeScript',
    'Python': 'Python',
    'Docker': 'Docker',
    'Kubernetes': 'Kubernetes',
    'AWS': 'AWS',
    'GCP': 'GCP',
    'Azure': 'Azure',
    'CI/CD': 'CI/CD',
    'CI': 'CI',
    'CD': 'CD',
    'Git': 'Git',
    'GitHub': 'GitHub',
    'GitLab': 'GitLab',
    'Slack': 'Slack',
    'Jira': 'Jira',

    # AWS Services
    'EC2': 'EC2 (compute)',
    'S3': 'S3 (storage)',
    'RDS': 'RDS (database)',
    'Lambda': 'Lambda (serverless)',
    'DynamoDB': 'DynamoDB (NoSQL)',
    'CloudFormation': 'CloudFormation (IaC)',
    'CloudWatch': 'CloudWatch (monitoring)',
    'CloudFront': 'CloudFront (CDN)',
    'CloudTrail': 'CloudTrail (audit)',
    'Cognito': 'Cognito (auth)',
    'API Gateway': 'API Gateway',
    'ECS': 'ECS (containers)',
    'EKS': 'EKS (Kubernetes)',
    'Fargate': 'Fargate (serverless containers)',
    'ALB': 'ALB (load balancer)',
    'NLB': 'NLB (network LB)',
    'EBS': 'EBS (block storage)',
    'VPC': 'VPC (network)',
    'IAM': 'IAM (permissions)',
    'KMS': 'KMS (encryption)',
    'SQS': 'SQS (queue)',
    'SNS': 'SNS (notifications)',
    'EventBridge': 'EventBridge (events)',
    'Kinesis': 'Kinesis (streaming)',
    'Glue': 'Glue (ETL)',
    'Athena': 'Athena (query)',
    'Redshift': 'Redshift (data warehouse)',
    'CodeBuild': 'CodeBuild',
    'CodeDeploy': 'CodeDeploy',
    'CodePipeline': 'CodePipeline',
    'Cost Explorer': 'Cost Explorer',
    'AMI': 'AMI (image)',

    # HTTP
    'GET': 'GET (read)',
    'POST': 'POST (create)',
    'PUT': 'PUT (update)',
    'PATCH': 'PATCH (partial update)',
    'DELETE': 'DELETE (remove)',
    '200': '200 (OK)',
    '201': '201 (Created)',
    '400': '400 (Bad Request)',
    '401': '401 (Unauthorized)',
    '403': '403 (Forbidden)',
    '404': '404 (Not Found)',
    '500': '500 (Server Error)',

    # Kubernetes
    'Pod': 'Pod',
    'Deployment': 'Deployment',
    'Service': 'Service',
    'ConfigMap': 'ConfigMap',
    'Secret': 'Secret',
    'Ingress': 'Ingress',
    'Namespace': 'Namespace',
    'Node': 'Node',
    'kubectl': 'kubectl',

    # Frontend
    'React': 'React',
    'Vue': 'Vue',
    'Angular': 'Angular',
    'Next.js': 'Next.js',
    'Nuxt': 'Nuxt',
    'Redux': 'Redux',
    'Webpack': 'Webpack',
    'Vite': 'Vite',
    'npm': 'npm',
    'yarn': 'yarn',
    'DOM': 'DOM',
    'SSR': 'SSR (server rendering)',
    'CSR': 'CSR (client rendering)',
    'SEO': 'SEO',
    'ARIA': 'ARIA (accessibility)',
    'Flexbox': 'Flexbox',
    'Grid': 'Grid',

    # Database
    'PostgreSQL': 'PostgreSQL',
    'MySQL': 'MySQL',
    'MongoDB': 'MongoDB',
    'Redis': 'Redis',
    'Elasticsearch': 'Elasticsearch',
    'JOIN': 'JOIN',
    'INDEX': 'INDEX',
    'PRIMARY KEY': 'PRIMARY KEY',
    'FOREIGN KEY': 'FOREIGN KEY',
    'NULL': 'NULL',
    'ORM': 'ORM',
    'Prisma': 'Prisma',

    # Security
    'CORS': 'CORS',
    'CSRF': 'CSRF',
    'XSS': 'XSS',
    'JWT': 'JWT (token)',
    'OAuth': 'OAuth',
    'SSO': 'SSO (single sign-on)',
    'MFA': 'MFA (multi-factor)',
    'SSL': 'SSL',
    'TLS': 'TLS',
    'HTTPS': 'HTTPS',
    'DDoS': 'DDoS (attack)',
    'WAF': 'WAF (firewall)',

    # Monitoring
    'Datadog': 'Datadog',
    'Grafana': 'Grafana',
    'Prometheus': 'Prometheus',
    'Sentry': 'Sentry',
    'APM': 'APM (performance)',
    'ELK': 'ELK (logging)',

    # DevOps
    'Terraform': 'Terraform (IaC)',
    'Ansible': 'Ansible',
    'Jenkins': 'Jenkins',
    'Dockerfile': 'Dockerfile',
    '.env': '.env (environment)',
    'nginx': 'nginx',

    # Misc
    'CDN': 'CDN',
    'DNS': 'DNS',
    'TCP': 'TCP',
    'UDP': 'UDP',
    'WebSocket': 'WebSocket',
    'gRPC': 'gRPC',
    'Blob': 'Blob (binary)',
    'Base64': 'Base64',
    'UUID': 'UUID',
    'CRON': 'CRON (scheduler)',
    'ETL': 'ETL (data pipeline)',
    'SDK': 'SDK',
    'CLI': 'CLI',
    'GUI': 'GUI',
    'IDE': 'IDE',
    'REPL': 'REPL',
    'DRY': 'DRY (don\'t repeat)',
    'SOLID': 'SOLID (principles)',
    'MVC': 'MVC (pattern)',
    'DTO': 'DTO (data transfer)',
    'DM': 'DM (direct message)',
    '1対1': 'one-on-one',

    # Actions with して
    '確認して': 'please check',
    '共有して': 'please share',
    '対応して': 'please handle',
    '検討して': 'please consider',
    '報告して': 'please report',
    '連絡して': 'please contact',
    '相談して': 'please consult',
    '調整して': 'please coordinate',
    '送って': 'please send',
    '教えて': 'please tell/teach',
    '見て': 'please look at',
    '待って': 'please wait',
    'お願い': 'please/favor',

    # Additional vocabulary from context
    '予定': 'schedule/plan',
    '変更点': 'changes',
    '原因': 'cause',
    '解決': 'solve',
    '影響': 'impact',
    '範囲': 'scope',
    '担当': 'in charge',
    '責任': 'responsibility',
    'メンバー': 'member',
    'チーム': 'team',
    'リーダー': 'leader',
    'マネージャー': 'manager',
    'エンジニア': 'engineer',
    'デザイナー': 'designer',
    '環境': 'environment',
    '本番': 'production',
    'ステージング': 'staging',
    '開発環境': 'dev environment',
    '検証': 'verification',
    '動作確認': 'operation check',
    '不具合': 'bug/defect',
    '障害': 'incident/failure',
    '復旧': 'recovery',
    '暫定対応': 'temporary fix',
    '恒久対応': 'permanent fix',
    '根本原因': 'root cause',
    'ワークアラウンド': 'workaround',
    'ホットフィックス': 'hotfix',
    'パッチ': 'patch',
    '緊急': 'urgent',
    '至急': 'ASAP',
    '重要': 'important',
    '優先度': 'priority',
    '高い': 'high',
    '低い': 'low',
    '中': 'medium',
    'ブロッカー': 'blocker',
    'クリティカル': 'critical',
    'メジャー': 'major',
    'マイナー': 'minor',

    # API Design
    'API設計': 'API design',
    'エンドポイント設計': 'endpoint design',
    'スキーマ設計': 'schema design',
    'DB設計': 'DB design',
    'インフラ設計': 'infra design',
    'アーキテクチャ': 'architecture',
    'マイクロサービス': 'microservices',
    'モノリス': 'monolith',
    'サーバーレス': 'serverless',

    # Testing
    'テストケース': 'test case',
    'テスト計画': 'test plan',
    'テスト結果': 'test results',
    '合格': 'pass',
    '不合格': 'fail',
    'スキップ': 'skip',
    'ペンディング': 'pending',
    'フレーキー': 'flaky',
    'リグレッション': 'regression',

    # Data processing
    'バッチ': 'batch',
    'ストリーム': 'stream',
    'キュー': 'queue',
    'パブリッシュ': 'publish',
    'サブスクライブ': 'subscribe',
    'プロデューサー': 'producer',
    'コンシューマー': 'consumer',
    'メッセージ': 'message',
    'ペイロード': 'payload',

    # Additional verbs and expressions
    '使う': 'use',
    '書く': 'write',
    '読む': 'read',
    '見る': 'look/see',
    '聞く': 'ask/listen',
    '言う': 'say',
    '思う': 'think',
    '知る': 'know',
    '分かる': 'understand',
    '出来る': 'can do',
    '入れる': 'put in/insert',
    '出す': 'take out/output',
    '動く': 'work/move',
    '動かす': 'run/operate',
    '止まる': 'stop',
    '始める': 'start',
    '終わる': 'end',
    '続ける': 'continue',
    '変える': 'change',
    '直る': 'be fixed',
    '壊れる': 'break',
    '落ちる': 'crash/fall',
    '上がる': 'go up',
    '下がる': 'go down',
    '増える': 'increase',
    '減る': 'decrease',
    '足りる': 'be enough',
    '足りない': 'not enough',
    '合う': 'match',
    '違う': 'differ',
    '同じ': 'same',
    '似ている': 'similar',
    '決める': 'decide',
    '選ぶ': 'choose',
    '探す': 'search',
    '見つける': 'find',
    '作る': 'create/make',
    '消す': 'delete/erase',
    '送る': 'send',
    '受け取る': 'receive',
    '待つ': 'wait',
    '急ぐ': 'hurry',
    '遅れる': 'be late',
    '間に合う': 'make it in time',
    'やってみる': 'try it',
    '取り組む': 'work on',
    '取り消す': 'cancel/undo',
    '置き換える': 'replace',
    '切り替える': 'switch',
    '組み込む': 'incorporate',
    '取り入れる': 'adopt',
    '引き継ぐ': 'hand over',
    '絞り込む': 'narrow down',
    '洗い出す': 'identify/list',
    '見積もる': 'estimate',
    '振り返る': 'look back/review',
    '立ち上げる': 'launch/start up',
    '落とし込む': 'implement/apply',
    '巻き戻す': 'rewind/rollback',

    # More technical terms
    'アサイン': 'assign',
    'イテレーション': 'iteration',
    'イニシャライズ': 'initialize',
    'インジェクション': 'injection',
    'インポート': 'import',
    'エクスポート': 'export',
    'オーバーライド': 'override',
    'オーバーロード': 'overload',
    'キャスト': 'cast',
    'コールスタック': 'call stack',
    'コンストラクタ': 'constructor',
    'シリアライズ': 'serialize',
    'スコア': 'score',
    'スレッド': 'thread',
    'センサー': 'sensor',
    'ソケット': 'socket',
    'チェイン': 'chain',
    'ディスパッチ': 'dispatch',
    'デストラクタ': 'destructor',
    'デバイス': 'device',
    'バインド': 'bind',
    'ハッシュ化': 'hash',
    'ブートストラップ': 'bootstrap',
    'プロセス': 'process',
    'ペイジネーション': 'pagination',
    'マッピング': 'mapping',
    'メタデータ': 'metadata',
    'モード': 'mode',
    'ユーティリティ': 'utility',
    'ラッパー': 'wrapper',
    'ランダム': 'random',
    'リファクタ': 'refactor',
    'リンク': 'link',
    'ループ': 'loop',
    'レンダリング': 'rendering',
    'ロケール': 'locale',

    # Numbers and time
    '数分': 'a few minutes',
    '数時間': 'a few hours',
    '数日': 'a few days',
    '2日': 'two days',
    '毎日': 'every day',
    '毎週': 'every week',
    '定期的': 'regularly',
    '不定期': 'irregular',
    '即座に': 'instantly',
    '徐々に': 'gradually',
    '最終的': 'finally',
    '一時的': 'temporary',
    '恒久的': 'permanent',
    '長期的': 'long-term',
    '短期的': 'short-term',

    # Quality and state
    '正常': 'normal',
    '異常': 'abnormal',
    '成功': 'success',
    '失敗': 'failure',
    '有効': 'valid/enabled',
    '無効': 'invalid/disabled',
    '安全': 'safe/secure',
    '危険': 'dangerous',
    '可能': 'possible',
    '不可能': 'impossible',
    '必須': 'required',
    '任意': 'optional',
    '公開': 'public',
    '非公開': 'private',
    '内部': 'internal',
    '外部': 'external',
    '上流': 'upstream',
    '下流': 'downstream',

    # More common phrases
    '先に': 'first/beforehand',
    '後から': 'afterwards',
    '途中': 'in the middle',
    '全体': 'entire/whole',
    '一部': 'part',
    '全部': 'all',
    '両方': 'both',
    'どちら': 'which',
    '他に': 'other',
    '特に': 'especially',
    '多分': 'probably',
    '絶対': 'absolutely',
    '一応': 'just in case',
    '念のため': 'just to be safe',
    'やはり': 'as expected',
    'ついに': 'finally',
    'そろそろ': 'soon/about time',
    'しばらく': 'for a while',
    'そもそも': 'in the first place',
    'とりあえず': 'for now',
    '結局': 'in the end',
    '最近': 'recently',
    'いつも': 'always',
    'たまに': 'sometimes',
    'よく': 'often/well',
    'あまり': 'not much',
    'ほとんど': 'almost/mostly',
    'ぜひ': 'by all means',
    '早速': 'right away',

    # Katakana loanwords
    'イメージ': 'image',
    'イングレス': 'ingress',
    'インストール': 'install',
    'インターセプター': 'interceptor',
    'インライン': 'inline',
    'ウォークスルー': 'walkthrough',
    'ウォームアップ': 'warm up',
    'エクスプロイト': 'exploit',
    'エスケープ': 'escape',
    'エッジ': 'edge',
    'エレガント': 'elegant',
    'エンティティ': 'entity',
    'オフセット': 'offset',
    'オブザーバー': 'observer',
    'オリジン': 'origin',
    'オンボーディング': 'onboarding',
    'オーナー': 'owner',
    'オーナーシップ': 'ownership',
    'カウント': 'count',
    'カウンター': 'counter',
    'カスケード': 'cascade',
    'カスタム': 'custom',
    'カーソル': 'cursor',
    'キー': 'key',
    'キープアライブ': 'keep-alive',
    'クライテリア': 'criteria',
    'クリーンアップ': 'cleanup',
    'クローズ': 'close',
    'クロスオリジン': 'cross-origin',
    'グルーピング': 'grouping',
    'グレースフル': 'graceful',
    'コア': 'core',
    'コピー': 'copy',
    'コミュニケーション': 'communication',
    'コレクション': 'collection',
    'コンソール': 'console',
    'コンテキスト': 'context',
    'コンテンツ': 'content',
    'コンバージョン': 'conversion',
    'コンパイル': 'compile',
    'コンポーネント': 'component',
    'コールド': 'cold',
    'サイクル': 'cycle',
    'サイズ': 'size',
    'サニタイズ': 'sanitize',
    'サブセット': 'subset',
    'サブネット': 'subnet',
    'サムネイル': 'thumbnail',
    'サンプル': 'sample',
    'シグナル': 'signal',
    'シナリオ': 'scenario',
    'シフト': 'shift',
    'シミュレーション': 'simulation',
    'シングルトン': 'singleton',
    'シンプル': 'simple',
    'シンボル': 'symbol',
    'ジェネリック': 'generic',
    'ジェネレーター': 'generator',
    'ジャンプ': 'jump',
    'スイッチ': 'switch',
    'スキャン': 'scan',
    'スクラッチ': 'scratch',
    'スクリプト': 'script',
    'スケール': 'scale',
    'スタイル': 'style',
    'ステップ': 'step',
    'ストア': 'store',
    'ストレージ': 'storage',
    'スプリット': 'split',
    'スペック': 'spec',
    'スポット': 'spot',
    'スマート': 'smart',
    'スリム': 'slim',
    'セグメント': 'segment',
    'セッション': 'session',
    'セットアップ': 'setup',
    'セマンティック': 'semantic',
    'ソリューション': 'solution',
    'タイプ': 'type',
    'タグ': 'tag',
    'ターゲット': 'target',
    'ターミナル': 'terminal',
    'ダイアグラム': 'diagram',
    'ダイジェスト': 'digest',
    'ダンプ': 'dump',
    'チェーン': 'chain',
    'チャンク': 'chunk',
    'チャンネル': 'channel',
    'ツリー': 'tree',
    'テキスト': 'text',
    'テスター': 'tester',
    'テナント': 'tenant',
    'テンプレート': 'template',
    'デコレーター': 'decorator',
    'デモ': 'demo',
    'データ': 'data',
    'データフロー': 'data flow',
    'トークン': 'token',
    'トップ': 'top',
    'トラッキング': 'tracking',
    'トラフィック': 'traffic',
    'トランスフォーム': 'transform',
    'ドキュメント': 'document',
    'ドライ': 'dry',
    'ドライバー': 'driver',
    'ドメイン': 'domain',
    'ネイティブ': 'native',
    'ネスト': 'nest',
    'ノイズ': 'noise',
    'ノーマライズ': 'normalize',
    'ハイブリッド': 'hybrid',
    'ハンドオフ': 'handoff',
    'バウンダリ': 'boundary',
    'バケット': 'bucket',
    'バックグラウンド': 'background',
    'バックプレッシャー': 'backpressure',
    'バッジ': 'badge',
    'バナー': 'banner',
    'パイロット': 'pilot',
    'パターン': 'pattern',
    'パッケージ': 'package',
    'パフォーマンス': 'performance',
    'パラレル': 'parallel',
    'ヒストリー': 'history',
    'ヒット': 'hit',
    'ビュー': 'view',
    'ピン': 'pin',
    'ファクトリー': 'factory',
    'フィルタリング': 'filtering',
    'フィンガープリント': 'fingerprint',
    'フェーズ': 'phase',
    'フォント': 'font',
    'フラット': 'flat',
    'フレキシブル': 'flexible',
    'フロー': 'flow',
    'ブランク': 'blank',
    'ブリッジ': 'bridge',
    'ブロードキャスト': 'broadcast',
    'プライベート': 'private',
    'プラグイン': 'plugin',
    'プレイスホルダー': 'placeholder',
    'プレビュー': 'preview',
    'プレフィックス': 'prefix',
    'プロトコル': 'protocol',
    'プロトタイプ': 'prototype',
    'プロパティ': 'property',
    'プロファイラー': 'profiler',
    'プロファイリング': 'profiling',
    'ベンチマーク': 'benchmark',
    'ペア': 'pair',
    'ホスト': 'host',
    'ポイント': 'point',
    'ポリシー': 'policy',
    'ポート': 'port',
    'マウント': 'mount',
    'マスキング': 'masking',
    'マスター': 'master',
    'マッチ': 'match',
    'マニフェスト': 'manifest',
    'ミックスイン': 'mixin',
    'ミラーリング': 'mirroring',
    'メイン': 'main',
    'メッシュ': 'mesh',
    'メモ': 'memo',
    'メンテナンスモード': 'maintenance mode',
    'モック': 'mock',
    'モニター': 'monitor',
    'ユニーク': 'unique',
    'ユニット': 'unit',
    'ライブラリ': 'library',
    'ラウンドロビン': 'round robin',
    'ラベル': 'label',
    'リクエスト': 'request',
    'リスク': 'risk',
    'リスト': 'list',
    'リセット': 'reset',
    'リダイレクト': 'redirect',
    'リトライ': 'retry',
    'リバース': 'reverse',
    'リビルド': 'rebuild',
    'リフレッシュ': 'refresh',
    'リプレース': 'replace',
    'リミット': 'limit',
    'リモートワーク': 'remote work',
    'リンター': 'linter',
    'ルックアップ': 'lookup',
    'ルーティング': 'routing',
    'ルール': 'rule',
    'レイヤー': 'layer',
    'レコード': 'record',
    'レスポンシブ': 'responsive',
    'レビュー': 'review',
    'レプリカセット': 'replica set',
    'レポート': 'report',
    'レンジ': 'range',
    'ロック': 'lock',
    'ログアウト': 'logout',
    'ログイン': 'login',
    'ロジカル': 'logical',
    'ロテーション': 'rotation',
    'ワイルドカード': 'wildcard',
    'ワークスペース': 'workspace',
    '上書き': 'overwrite',
    '下位互換': 'backward compatible',
    '事前': 'beforehand',
    '事後': 'afterward',
    '予測': 'predict',
    '代替': 'alternative',
    '伝える': 'convey/tell',
    '使い方': 'how to use',
    '例外処理': 'exception handling',
    '依存': 'depend',
    '保守': 'maintain',
    '保持': 'retain/hold',
    '修正中': 'fixing',
    '修復': 'repair',
    '候補': 'candidate',
    '入力値': 'input value',
    '再利用': 'reuse',
    '再実行': 're-run',
    '再帰': 'recursive',
    '出力値': 'output value',
    '分割': 'split/divide',
    '分離': 'separate',
    '初期': 'initial',
    '削減': 'reduce',
    '効率': 'efficiency',
    '動作': 'behavior',
    '動的型付け': 'dynamic typing',
    '匿名': 'anonymous',
    '参照': 'reference',
    '取得': 'get/retrieve',
    '受信': 'receive',
    '合計': 'total',
    '同時': 'simultaneous',
    '同期的': 'synchronous',
    '命名': 'naming',
    '固定': 'fixed',
    '圧縮率': 'compression ratio',
    '基盤': 'foundation',
    '堅牢': 'robust',
    '境界': 'boundary',
    '増加': 'increase',
    '増幅': 'amplify',
    '変形': 'transform',
    '外注': 'outsource',
    '多重': 'multiple',
    '完成': 'complete',
    '実現': 'realize/achieve',
    '実績': 'track record',
    '実装済み': 'implemented',
    '対処': 'deal with',
    '対象': 'target/subject',
    '対策': 'countermeasure',
    '対話': 'interactive',
    '導入': 'introduce',
    '差分': 'diff',
    '常に': 'always',
    '平均': 'average',
    '廃止予定': 'deprecated',
    '形式': 'format',
    '形状': 'shape',
    '従来': 'conventional',
    '循環': 'circular',
    '性能': 'performance',
    '悪化': 'worsen',
    '想定': 'assume',
    '意図': 'intent',
    '戻す': 'restore',
    '抑制': 'suppress',
    '抽出': 'extract',
    '抽象化': 'abstraction',
    '拡張': 'extend',
    '拡張性': 'extensibility',
    '指定': 'specify',
    '挙動': 'behavior',
    '排他': 'exclusive',
    '排除': 'exclude',
    '推測': 'guess',
    '推論': 'infer',
    '描画': 'draw/render',
    '提供': 'provide',
    '提案': 'propose',
    '提示': 'present',
    '改善': 'improve',
    '改良': 'improve',
    '整理': 'organize',
    '整備': 'prepare',
    '文字化け': 'garbled text',
    '文字数': 'character count',
    '既存': 'existing',
    '明示的': 'explicit',
    '暗黙的': 'implicit',
    '最大': 'maximum',
    '最小': 'minimum',
    '最新': 'latest',
    '最適': 'optimal',
    '期待': 'expect',
    '未対応': 'not supported',
    '未定': 'TBD',
    '未実装': 'not implemented',
    '未知': 'unknown',
    '本来': 'originally',
    '柔軟': 'flexible',
    '検出': 'detect',
    '検知': 'detect',
    '構築': 'build/construct',
    '概念': 'concept',
    '概要': 'overview',
    '模倣': 'mimic',
    '正規化': 'normalize',
    '正規表現': 'regex',
    '比較': 'compare',
    '永続': 'persistent',
    '決定': 'decide',
    '注入': 'inject',
    '派生': 'derived',
    '消費': 'consume',
    '混在': 'mixed',
    '減少': 'decrease',
    '測定': 'measure',
    '準拠': 'compliant',
    '漏れ': 'leak',
    '無限': 'infinite',
    '独自': 'unique/custom',
    '現状': 'current state',
    '生成': 'generate',
    '生成中': 'generating',
    '番号': 'number',
    '登録': 'register',
    '発火': 'fire/trigger',
    '発生': 'occur',
    '発行': 'issue/publish',
    '監査ログ': 'audit log',
    '相互': 'mutual',
    '確率': 'probability',
    '移動': 'move',
    '空': 'empty',
    '突然': 'suddenly',
    '管理': 'manage',
    '管理者': 'admin',
    '組み合わせ': 'combination',
    '経由': 'via',
    '結合': 'join/combine',
    '絞り込み': 'filter',
    '統一': 'unify',
    '統計': 'statistics',
    '維持': 'maintain',
    '継承': 'inherit',
    '続行': 'continue',
    '網羅': 'comprehensive',
    '緩和': 'mitigate',
    '置換': 'replace',
    '考慮': 'consider',
    '肥大化': 'bloat',
    '自動': 'automatic',
    '自身': 'self',
    '若干': 'slightly',
    '落とす': 'drop',
    '蓄積': 'accumulate',
    '行列': 'queue',
    '補完': 'complement',
    '複合': 'compound',
    '複数': 'multiple',
    '複雑': 'complex',
    '要約': 'summarize',
    '見落とし': 'oversight',
    '規約': 'convention',
    '規模': 'scale',
    '解放': 'release',
    '解決策': 'solution',
    '言語': 'language',
    '記録': 'record',
    '試験': 'test',
    '認識': 'recognize',
    '識別': 'identify',
    '警告': 'warning',
    '負債': 'debt',
    '負荷': 'load',
    '資源': 'resource',
    '起動中': 'starting',
    '転送': 'transfer',
    '辞書': 'dictionary',
    '配置': 'place/deploy',
    '配布': 'distribute',
    '重複': 'duplicate',
    '長さ': 'length',
    '閉じる': 'close',
    '開始': 'start',
    '開発中': 'in development',
    '関連': 'related',
    '除外': 'exclude',
    '階層': 'hierarchy',
    '集約': 'aggregate',
    '集計': 'aggregate',
    '非同期処理': 'async processing',
    '順序': 'sequence',
    '頻度': 'frequency',
    '頻繁': 'frequent',

    # More remaining terms
    'CI/CD': 'CI/CD',
    'カナリア': 'canary',
    'カプセル化': 'encapsulation',
    'カラム': 'column',
    'ガード': 'guard',
    'キックオフ': 'kickoff',
    'キャンセル': 'cancel',
    'キーローテーション': 'key rotation',
    'グラフ': 'graph',
    'グリーンフィールド': 'greenfield',
    'グルーミング': 'grooming',
    'コントラクト': 'contract',
    'コンフリクト': 'conflict',
    'コード分割': 'code splitting',
    'サンセット': 'sunset',
    'シリアライゼーション': 'serialization',
    'ジョイン': 'join',
    'スカッシュ': 'squash',
    'スキル': 'skill',
    'スクリーンショット': 'screenshot',
    'スクロール': 'scroll',
    'スケーラブル': 'scalable',
    'スケーラビリティ': 'scalability',
    'スタンダード': 'standard',
    'スタンバイ': 'standby',
    'ストラテジー': 'strategy',
    'スロットリング': 'throttling',
    'スロット': 'slot',
    'スワップ': 'swap',
    'セキュア': 'secure',
    'セルフサービス': 'self-service',
    'センシティブ': 'sensitive',
    'タイミング': 'timing',
    'タイムゾーン': 'timezone',
    'タイムスタンプ': 'timestamp',
    'ダッシュボード': 'dashboard',
    'ダブルチェック': 'double check',
    'チケット': 'ticket',
    'チューン': 'tune',
    'ツールチェーン': 'toolchain',
    'ディスク': 'disk',
    'ディレイ': 'delay',
    'テーブル': 'table',
    'デコード': 'decode',
    'デコンポーズ': 'decompose',
    'デッドレター': 'dead letter',
    'デッドライン': 'deadline',
    'デバッグモード': 'debug mode',
    'デプロイ': 'deploy',
    'デリート': 'delete',
    'トークナイザー': 'tokenizer',
    'トラブル': 'trouble',
    'トランザクション': 'transaction',
    'トランスレート': 'translate',
    'トリム': 'trim',
    'トレース': 'trace',
    'ドライラン': 'dry run',
    'ドロップ': 'drop',
    'ナレッジ': 'knowledge',
    'ネガティブ': 'negative',
    'ネットワークポリシー': 'network policy',
    'ノーコード': 'no-code',
    'ノーマル': 'normal',
    'ハードウェア': 'hardware',
    'ハイパフォーマンス': 'high performance',
    'ハッカソン': 'hackathon',
    'バインディング': 'binding',
    'バグ修正': 'bug fix',
    'バッチ処理': 'batch processing',
    'バリアント': 'variant',
    'バージョニング': 'versioning',
    'バージョン管理': 'version control',
    'パケット': 'packet',
    'パス': 'path',
    'パッシブ': 'passive',
    'パブリック': 'public',
    'パラダイム': 'paradigm',
    'パーサー': 'parser',
    'パーシャル': 'partial',
    'パーセント': 'percent',
    'パーティション': 'partition',
    'パーミッション': 'permission',
    'ヒープ': 'heap',
    'ビジュアライゼーション': 'visualization',
    'ビット': 'bit',
    'ピボット': 'pivot',
    'ファイナライズ': 'finalize',
    'ファイルシステム': 'file system',
    'フィックス': 'fix',
    'フィード': 'feed',
    'フック': 'hook',
    'フッタ': 'footer',
    'フッター': 'footer',
    'フレーム': 'frame',
    'フレームワーク': 'framework',
    'ブレークポイント': 'breakpoint',
    'ブレーンストーミング': 'brainstorming',
    'プッシュ': 'push',
    'プリント': 'print',
    'プル': 'pull',
    'プルリクエストレビュー': 'PR review',
    'プロキシー': 'proxy',
    'プログレス': 'progress',
    'プロジェクト': 'project',
    'プロセッサ': 'processor',
    'プロダクト': 'product',
    'プロバイダ': 'provider',
    'プロバイダー': 'provider',
    'プロンプト': 'prompt',
    'ベンダー': 'vendor',
    'ベータ': 'beta',
    'ヘッダ': 'header',
    'ペイロード': 'payload',
    'ペースト': 'paste',
    'ホイールレース': 'wheel race',
    'ポジティブ': 'positive',
    'ポストバック': 'postback',
    'ポスト処理': 'post-processing',
    'マージコンフリクト': 'merge conflict',
    'マイナーバージョン': 'minor version',
    'マクロ': 'macro',
    'マネージド': 'managed',
    'マルチテナント': 'multi-tenant',
    'マルチプロセス': 'multi-process',
    'ミッション': 'mission',
    'ミドル': 'middle',
    'メジャーバージョン': 'major version',
    'メッセージキュー': 'message queue',
    'メッセージング': 'messaging',
    'メモリ': 'memory',
    'メモリー': 'memory',
    'モジュラー': 'modular',
    'モバイル': 'mobile',
    'ユーザー': 'user',
    'ユーザビリティ': 'usability',
    'ラッチ': 'latch',
    'ランキング': 'ranking',
    'リアクティブ': 'reactive',
    'リアルタイム': 'real-time',
    'リカバリ': 'recovery',
    'リキュー': 'requeue',
    'リグレッション': 'regression',
    'リスケ': 'reschedule',
    'リスケジュール': 'reschedule',
    'リゾルバ': 'resolver',
    'リトライロジック': 'retry logic',
    'リバランス': 'rebalance',
    'リファクタリング': 'refactoring',
    'リフレクション': 'reflection',
    'リベース': 'rebase',
    'リボーク': 'revoke',
    'リムーブ': 'remove',
    'リリース': 'release',
    'リンクチェック': 'link check',
    'ルートパス': 'root path',
    'ルート': 'root',
    'レイジー': 'lazy',
    'レシピ': 'recipe',
    'レジリエンス': 'resilience',
    'レジリエント': 'resilient',
    'レスポンス': 'response',
    'レトロスペクティブ': 'retrospective',
    'レバレッジ': 'leverage',
    'レプリカ': 'replica',
    'ローカライズ': 'localize',
    'ローカル': 'local',
    'ログレベル': 'log level',
    'ロット': 'lot',
    'ロールアウト': 'rollout',
    'ロールバック': 'rollback',
    'ロール': 'role',
    'ワークアラウンド': 'workaround',
    'ワークロード': 'workload',
    'ワーニング': 'warning',
    '一括': 'batch/bulk',
    '一覧': 'list',
    '一貫性': 'consistency',
    '不具合': 'defect/bug',
    '中断': 'interrupt',
    '予約': 'reserve',
    '交換': 'exchange',
    '仮想': 'virtual',
    '仮想化': 'virtualization',
    '付与': 'grant',
    '件数': 'count',
    '以降': 'from/since',
    '休止': 'pause',
    '伸縮': 'elastic',
    '低下': 'decrease',
    '体験': 'experience',
    '何か': 'something',
    '保護': 'protect',
    '保管': 'store',
    '修正済み': 'fixed',
    '個別': 'individual',
    '値': 'value',
    '健全': 'healthy',
    '健全性': 'health',
    '偽': 'false',
    '優先度高': 'high priority',
    '充足': 'sufficient',
    '先延ばし': 'postpone',
    '入出力': 'I/O',
    '全文検索': 'full-text search',
    '公式': 'official',
    '共通': 'common',
    '内訳': 'breakdown',
    '再送': 'resend',
    '凍結': 'freeze',
    '処理中': 'processing',
    '出力': 'output',
    '分岐': 'branch',
    '分類': 'classify',
    '切り分け': 'isolate',
    '列': 'column/row',
    '初回': 'first time',
    '別名': 'alias',
    '到達': 'reach',
    '制御': 'control',
    '前提': 'prerequisite',
    '前提条件': 'prerequisite',
    '割り当て': 'assign',
    '効果': 'effect',
    '単一': 'single',
    '単位': 'unit',
    '単体': 'unit/single',
    '単調': 'monotonic',
    '危機的': 'critical',
    '原則': 'principle',
    '参画': 'participate',
    '反映': 'reflect',
    '取り扱い': 'handling',
    '受け入れ': 'accept',
    '受領': 'receive',
    '回帰': 'regression',
    '回数': 'count/times',
    '回復': 'recover',
    '回避': 'avoid',
    '国際化': 'i18n',
    '地域化': 'l10n',
    '均等': 'equal',
    '型安全': 'type safe',
    '埋め込み': 'embed',
    '基準': 'baseline',
    '堅固': 'solid',
    '増強': 'enhance',
    '壊す': 'break',
    '外す': 'remove',
    '大量': 'large amount',
    '失効': 'expire',
    '契約': 'contract',
    '安定版': 'stable version',
    '実行中': 'running',
    '実稼働': 'production',
    '密接': 'close/tight',
    '対比': 'contrast',
    '専門': 'specialty',
    '専用': 'dedicated',
    '小さい': 'small',
    '少数': 'few',
    '巨大': 'huge',
    '差し替え': 'replace',
    '差異': 'difference',
    '帰属': 'belong',
    '常時': 'always',
    '干渉': 'interference',
    '平行': 'parallel',
    '幅': 'width',
    '度': 'degree/times',
    '強制': 'force',
    '待機': 'wait/standby',
    '待機中': 'waiting',
    '従属': 'dependent',
    '得る': 'obtain',
    '復元': 'restore',
    '必然': 'inevitable',
    '応答': 'response',
    '忘れ': 'forget',
    '急': 'urgent',
    '情報': 'information',
    '感度': 'sensitivity',
    '戦略': 'strategy',
    '手動': 'manual',
    '手順': 'procedure',
    '承知': 'acknowledge',
    '折り返し': 'callback',
    '抜ける': 'exit/missing',
    '抽象': 'abstract',
    '持続': 'persist',
    '指示': 'instruction',
    '挿入': 'insert',
    '捕捉': 'capture',
    '排他制御': 'exclusive control',
    '採用': 'adopt',
    '接頭辞': 'prefix',
    '接尾辞': 'suffix',
    '推進': 'promote',
    '撤回': 'withdraw',
    '撤去': 'remove',
    '操作': 'operation',
    '支障': 'hindrance',
    '改修': 'modify',
    '放棄': 'abandon',
    '整形': 'format',
    '方向': 'direction',
    '方針': 'policy',
    '旧': 'old',
    '昇格': 'promote',
    '時刻': 'time',
    '時差': 'time difference',
    '時系列': 'time series',
    '更改': 'update',
    '最優先': 'top priority',
    '最低': 'minimum',
    '有効化': 'enable',
    '有無': 'presence',
    '本体': 'main body',
    '本番稼働': 'production',
    '条件': 'condition',
    '条件分岐': 'conditional branch',
    '来る': 'come',
    '枯渇': 'exhaustion',
    '柱': 'pillar',
    '桁': 'digit',
    '棄却': 'reject',
    '植え込み': 'embed',
    '様式': 'format',
    '横断': 'cross',
    '横断的': 'cross-cutting',
    '機密': 'confidential',
    '機密性': 'confidentiality',
    '機構': 'mechanism',
    '正確': 'accurate',
    '正解': 'correct',
    '残す': 'leave',
    '残存': 'remaining',
    '段階': 'stage',
    '比例': 'proportion',
    '気づく': 'notice',
    '永久': 'permanent',
    '決め打ち': 'hardcode',
    '決済': 'payment',
    '法則': 'law',
    '活用': 'utilize',
    '流入': 'inflow',
    '流出': 'outflow',
    '流量': 'flow rate',
    '消去': 'erase',
    '深さ': 'depth',
    '深掘り': 'deep dive',
    '混乱': 'confusion',
    '清掃': 'cleanup',
    '渡す': 'pass',
    '測る': 'measure',
    '溢れ': 'overflow',
    '滞留': 'stagnation',
    '漸進': 'gradual',
    '点検': 'inspection',
    '無停止': 'zero downtime',
    '無視': 'ignore',
    '焦点': 'focus',
    '照合': 'match',
    '特化': 'specialize',
    '特定': 'identify',
    '特性': 'characteristic',
    '狭い': 'narrow',
    '独立': 'independent',
    '狙い': 'aim',
    '現地': 'local',
    '現行': 'current',
    '現象': 'phenomenon',
    '理解': 'understand',
    '環境変数': 'env variable',
    '生産': 'production',
    '用意': 'prepare',
    '用途': 'purpose',
    '申請': 'application',
    '画面': 'screen',
    '画面遷移': 'screen transition',
    '発展': 'develop',
    '登場': 'appear',
    '目安': 'guideline',
    '目標': 'goal',
    '目的': 'purpose',
    '直感': 'intuition',
    '直感的': 'intuitive',
    '相性': 'compatibility',
    '相当': 'equivalent',
    '省略': 'omit',
    '真': 'true',
    '着手': 'start',
    '知見': 'insight',
    '短縮': 'shorten',
    '短絡': 'short circuit',
    '破損': 'corrupt',
    '破棄': 'discard',
    '硬い': 'rigid',
    '確保': 'secure',
    '確定': 'confirm',
    '確定的': 'deterministic',
    '確認済み': 'confirmed',
    '移行期': 'transition',
    '程度': 'degree',
    '積極的': 'proactive',
    '穴': 'hole',
    '突破': 'break through',
    '立案': 'plan',
    '競合状態': 'race condition',
    '第一': 'first',
    '等価': 'equivalent',
    '算出': 'calculate',
    '精査': 'examine',
    '紐付け': 'link',
    '終端': 'termination',
    '組み立て': 'assemble',
    '経路': 'route',
    '経過': 'elapsed',
    '結果': 'result',
    '結論': 'conclusion',
    '給付': 'provide',
    '続き': 'continuation',
    '緊急度': 'urgency',
    '総数': 'total count',
    '総量': 'total amount',
    '緩める': 'loosen',
    '繰り返し': 'repeat',
    '置く': 'put',
    '群': 'group',
    '背景': 'background',
    '脆い': 'fragile',
    '自動テスト': 'auto test',
    '自明': 'obvious',
    '良い': 'good',
    '行': 'row/line',
    '表': 'table',
    '表現': 'expression',
    '裏': 'back',
    '補助': 'assist',
    '製品': 'product',
    '複写': 'copy',
    '見た目': 'appearance',
    '見極め': 'assess',
    '規則': 'rule',
    '規格': 'standard',
    '視覚化': 'visualize',
    '解凍': 'decompress',
    '解除': 'release',
    '計測': 'measure',
    '記載': 'describe',
    '記述': 'description',
    '許可': 'permit',
    '設問': 'question',
    '診断': 'diagnose',
    '評価基準': 'criteria',
    '詰まり': 'clog',
    '読み取り': 'read',
    '調子': 'condition',
    '論理': 'logic',
    '謎': 'mystery',
    '警報': 'alarm',
    '責任者': 'person in charge',
    '質': 'quality',
    '購入': 'purchase',
    '起点': 'starting point',
    '起源': 'origin',
    '超える': 'exceed',
    '跨ぐ': 'span',
    '軽減': 'reduce',
    '載せる': 'load',
    '輻輳': 'congestion',
    '辿る': 'trace',
    '送出': 'send out',
    '逆': 'reverse',
    '通常': 'normal',
    '速度': 'speed',
    '連動': 'link',
    '連鎖': 'chain',
    '進む': 'proceed',
    '進行': 'progress',
    '遅れ': 'delay',
    '過剰': 'excess',
    '過負荷': 'overload',
    '達成': 'achieve',
    '選定': 'select',
    '選別': 'sort',
    '遷移': 'transition',
    '配備': 'deploy',
    '配送': 'deliver',
    '重み': 'weight',
    '量': 'amount',
    '鍵': 'key',
    '開放': 'open',
    '閲覧': 'view',
    '防ぐ': 'prevent',
    '防止': 'prevent',
    '限界': 'limit',
    '限度': 'limit',
    '隔離': 'isolate',
    '集中': 'concentrate',
    '雛形': 'template',
    '非同期': 'asynchronous',
    '面倒': 'troublesome',
    '順守': 'comply',
    '頭': 'head',
    '類似': 'similar',
    '飽和': 'saturation',
    '高い': 'high',
    '高速': 'fast',

    # Final batch
    'スケジューラ': 'scheduler',
    'スタッシュ': 'stash',
    'ステークホルダー': 'stakeholder',
    'スパイ': 'spy',
    'スパン': 'span',
    'セキュリティ': 'security',
    'ソルト': 'salt',
    'タイトル': 'title',
    'チャート': 'chart',
    'ティアダウン': 'teardown',
    'トランジション': 'transition',
    'トレーシング': 'tracing',
    'トースト': 'toast',
    'ハイドレーション': 'hydration',
    'ハッキー': 'hacky',
    'ハッピーパス': 'happy path',
    'ハンドル': 'handle',
    'ハードコード': 'hardcode',
    'バランス': 'balance',
    'バリュー': 'value',
    'バンドル': 'bundle',
    'パスワード': 'password',
    'パターンマッチ': 'pattern match',
    'パッド': 'pad',
    'パネル': 'panel',
    'パラメーター': 'parameter',
    'ヒント': 'hint',
    'ファサード': 'facade',
    'フィールド': 'field',
    'フェイク': 'fake',
    'フォーカス': 'focus',
    'フラッシュ': 'flush',
    'ブースト': 'boost',
    'ブート': 'boot',
    'プライマリ': 'primary',
    'プリセット': 'preset',
    'プリンシパル': 'principal',
    'プレーン': 'plain',
    'プロビジョン': 'provision',
    'プロンプター': 'prompter',
    'ベクター': 'vector',
    'ベース': 'base',
    'ペイン': 'pane',
    'ペルソナ': 'persona',
    'ホワイトリスト': 'whitelist',
    'ボックス': 'box',
    'ポイント': 'point',
    'マーク': 'mark',
    'ミュート': 'mute',
    'メインテナンス': 'maintenance',
    'メカニズム': 'mechanism',
    'メッセージ': 'message',
    'メンテ': 'maintenance',
    'モデル': 'model',
    'モンキーパッチ': 'monkey patch',
    'ユニファイ': 'unify',
    'ライトウェイト': 'lightweight',
    'ライフサイクルフック': 'lifecycle hook',
    'ラウンドトリップ': 'round trip',
    'ラッシュ': 'rush',
    'リアクト': 'react',
    'リコール': 'recall',
    'リザーブ': 'reserve',
    'リターン': 'return',
    'リデュース': 'reduce',
    'リトル': 'little',
    'リプレイ': 'replay',
    'リプロダクション': 'reproduction',
    'リード': 'lead/read',
    'ルックアヘッド': 'lookahead',
    'ルーター': 'router',
    'レイアウト': 'layout',
    'レキシカル': 'lexical',
    'レガシーコード': 'legacy code',
    'レジューム': 'resume',
    'レストア': 'restore',
    'レート': 'rate',
    'レートリミット': 'rate limit',
    'レールガード': 'rail guard',
    'ロギング': 'logging',
    'ロジカル': 'logical',
    'ワイド': 'wide',
    'ワンライナー': 'one-liner',
    '上位': 'upper',
    '下位': 'lower',
    '中心': 'center',
    '中身': 'content',
    '主': 'main',
    '主体': 'subject',
    '予備': 'backup',
    '事項': 'matter',
    '互換性チェック': 'compatibility check',
    '交差': 'intersection',
    '人気': 'popular',
    '代入': 'assign',
    '代表': 'representative',
    '仕様書': 'specification',
    '付属': 'attached',
    '付随': 'accompanying',
    '代わり': 'instead',
    '仕組み': 'mechanism',
    '他の': 'other',
    '以上': 'or more',
    '以下': 'or less',
    '以外': 'except',
    '以内': 'within',
    '件': 'case',
    '伝搬': 'propagate',
    '位置': 'position',
    '低コスト': 'low cost',
    '体系': 'system',
    '体裁': 'format',
    '何度': 'how many times',
    '余裕': 'margin',
    '作業': 'work',
    '例': 'example',
    '個数': 'count',
    '倍': 'times',
    '停止中': 'stopped',
    '側': 'side',
    '兼ねる': 'double as',
    '写真': 'photo',
    '冒頭': 'beginning',
    '処置': 'treatment',
    '出口': 'exit',
    '出番': 'turn',
    '分析結果': 'analysis result',
    '分断': 'divide',
    '判断': 'judge',
    '別途': 'separately',
    '利点': 'advantage',
    '利用': 'use',
    '到達率': 'reach rate',
    '制作': 'create',
    '制定': 'establish',
    '前回': 'last time',
    '前後': 'around',
    '前段': 'previous',
    '割合': 'ratio',
    '力': 'power',
    '加工': 'process',
    '加速': 'accelerate',
    '動き': 'movement',
    '勤務': 'work',
    '区分': 'category',
    '区別': 'distinguish',
    '区画': 'section',
    '十分': 'enough',
    '半分': 'half',
    '協力': 'cooperate',
    '単純': 'simple',
    '危うい': 'risky',
    '即時': 'immediate',
    '原因究明': 'root cause analysis',
    '原因調査': 'investigate cause',
    '参考': 'reference',
    '受ける': 'receive',
    '受付': 'reception',
    '古い': 'old',
    '可視': 'visible',
    '可視性': 'visibility',
    '可読性': 'readability',
    '右': 'right',
    '合わせる': 'match',
    '合理的': 'rational',
    '含む': 'include',
    '周囲': 'surroundings',
    '周期': 'cycle',
    '問い合わせ': 'inquiry',
    '回る': 'go around',
    '固める': 'solidify',
    '場合': 'case',
    '場所': 'place',
    '塊': 'chunk',
    '壁': 'wall',
    '多い': 'many',
    '多様': 'diverse',
    '大きい': 'large',
    '大幅': 'significant',
    '失う': 'lose',
    '奥': 'back/deep',
    '妥当': 'appropriate',
    '妥当性': 'validity',
    '学ぶ': 'learn',
    '定番': 'standard',
    '定数': 'constant',
    '対応中': 'responding',
    '対等': 'equal',
    '専有': 'exclusive',
    '小': 'small',
    '小数': 'decimal',
    '少ない': 'few',
    '尤度': 'likelihood',
    '履歴': 'history',
    '層': 'layer',
    '工夫': 'devise',
    '左': 'left',
    '差': 'difference',
    '帳票': 'form',
    '平均値': 'average',
    '平坦': 'flat',
    '年': 'year',
    '幅広い': 'wide',
    '序盤': 'early stage',
    '序列': 'order',
    '底': 'bottom',
    '度合い': 'degree',
    '座標': 'coordinates',
    '延長': 'extend',
    '建て替え': 'rebuild',
    '強化': 'strengthen',
    '強弱': 'strength',
    '強度': 'intensity',
    '強調': 'emphasize',
    '形': 'shape',
    '役割': 'role',
    '待ち': 'waiting',
    '後回し': 'postpone',
    '後方': 'rear',
    '徹底': 'thorough',
    '復帰': 'return',
    '心配なし': 'no worries',
    '必須項目': 'required field',
    '応急': 'emergency',
    '思い出す': 'remember',
    '性質': 'nature',
    '恐らく': 'probably',
    '悩み': 'problem',
    '意味': 'meaning',
    '意識': 'awareness',
    '感じる': 'feel',
    '感触': 'feel',
    '成果': 'result',
    '成長': 'grow',
    '戻り': 'return',
    '所要': 'required',
    '手元': 'at hand',
    '手段': 'means',
    '手法': 'method',
    '手間': 'effort',
    '抜く': 'extract',
    '把握する': 'grasp',
    '投入': 'input',
    '折れ線': 'line graph',
    '抽象クラス': 'abstract class',
    '抽象度': 'abstraction level',
    '担保': 'guarantee',
    '拒否': 'reject',
    '持つ': 'have',
    '指す': 'point',
    '挙げる': 'list',
    '捨てる': 'discard',
    '排他的': 'exclusive',
    '掘り下げ': 'dig deeper',
    '探索': 'search',
    '接続先': 'connection target',
    '推奨値': 'recommended value',
    '描く': 'draw',
    '揃える': 'align',
    '支援': 'support',
    '改ざん': 'tamper',
    '放置': 'leave',
    '既知': 'known',
    '明確': 'clear',
    '易い': 'easy',
    '時点': 'point in time',
    '時間': 'time',
    '暫定': 'temporary',
    '最短': 'shortest',
    '最長': 'longest',
    '有利': 'advantageous',
    '有力': 'influential',
    '有名': 'famous',
    '期日': 'due date',
    '期間': 'period',
    '未満': 'less than',
    '末尾': 'end',
    '本格': 'full-scale',
    '束ねる': 'bundle',
    '枠': 'frame',
    '柔らかい': 'soft',
    '根幹': 'core',
    '根拠': 'basis',
    '案': 'plan',
    '業務': 'business',
    '極端': 'extreme',
    '構成要素': 'component',
    '様々': 'various',
    '標準': 'standard',
    '標準化': 'standardize',
    '機会': 'opportunity',
    '正当': 'legitimate',
    '正式': 'official',
    '残る': 'remain',
    '殺す': 'kill',
    '母体': 'parent',
    '母数': 'population',
    '比率': 'ratio',
    '水平': 'horizontal',
    '汚れ': 'dirty',
    '決まり': 'rule',
    '流れ': 'flow',
    '浅い': 'shallow',
    '浸透': 'penetrate',
    '消える': 'disappear',
    '深い': 'deep',
    '混合': 'mix',
    '添付': 'attach',
    '温度': 'temperature',
    '準備中': 'preparing',
    '漏洩': 'leak',
    '潜在': 'potential',
    '点': 'point',
    '無制限': 'unlimited',
    '無名': 'anonymous',
    '無関係': 'unrelated',
    '熟成': 'mature',
    '物理': 'physical',
    '特': 'special',
    '特例': 'exception',
    '状況': 'situation',
    '狭義': 'narrow sense',
    '独占': 'monopoly',
    '率': 'rate',
    '現場': 'site',
    '現実': 'reality',
    '現物': 'actual',
    '理想': 'ideal',
    '環境': 'environment',
    '生存': 'survive',
    '生成物': 'product',
    '用語': 'term',
    '用語集': 'glossary',
    '画像': 'image',
    '異なる': 'differ',
    '疑問': 'question',
    '発信': 'send',
    '発表': 'announce',
    '発覚': 'discover',
    '発達': 'develop',
    '監視': 'monitor',
    '目印': 'mark',
    '目次': 'table of contents',
    '直列': 'serial',
    '相違': 'difference',
    '真ん中': 'middle',
    '知らせ': 'notice',
    '矛盾': 'contradiction',
    '砕ける': 'break',
    '確かめる': 'verify',
    '示す': 'show',
    '祝い': 'celebration',
    '秒': 'second',
    '秘匿': 'secret',
    '移す': 'move',
    '稀': 'rare',
    '空白': 'blank',
    '空間': 'space',
    '端': 'edge',
    '端末': 'terminal',
    '粒度': 'granularity',
    '素早い': 'quick',
    '素朴': 'simple',
    '終点': 'end point',
    '組み': 'set',
    '経験': 'experience',
    '結びつける': 'connect',
    '継続': 'continue',
    '繋がる': 'connect',
    '繋げる': 'connect',
    '繰り返す': 'repeat',
    '置換え': 'replace',
    '義務': 'obligation',
    '習慣': 'habit',
    '考える': 'think',
    '聞き取り': 'hearing',
    '背後': 'behind',
    '能力': 'ability',
    '自体': 'itself',
    '至る': 'reach',
    '良さ': 'goodness',
    '色々': 'various',
    '苦手': 'weak at',
    '蓋': 'lid',
    '行動': 'action',
    '表明': 'declare',
    '表記': 'notation',
    '補う': 'supplement',
    '補強': 'reinforce',
    '要': 'essential',
    '要件定義': 'requirements def',
    '要因': 'factor',
    '要素': 'element',
    '見た': 'saw',
    '見方': 'viewpoint',
    '見込み': 'prospect',
    '解く': 'solve',
    '解消': 'resolve',
    '言い換え': 'paraphrase',
    '計画書': 'plan document',
    '記事': 'article',
    '設ける': 'establish',
    '設置': 'install',
    '許容': 'tolerance',
    '詳しい': 'detailed',
    '誘発': 'induce',
    '説得': 'persuade',
    '課題': 'issue',
    '調べる': 'investigate',
    '諦める': 'give up',
    '識別子': 'identifier',
    '象徴': 'symbol',
    '貢献': 'contribute',
    '貯める': 'save',
    '起こる': 'happen',
    '起こす': 'cause',
    '起因': 'cause',
    '足す': 'add',
    '跡': 'trace',
    '身': 'body',
    '軽い': 'light',
    '輝く': 'shine',
    '込む': 'include',
    '近い将来': 'near future',
    '返す': 'return',
    '迷う': 'hesitate',
    '追う': 'chase',
    '追加する': 'add',
    '逃す': 'miss',
    '通す': 'pass through',
    '速い': 'fast',
    '連結': 'connect',
    '進める': 'advance',
    '遅延': 'delay',
    '過程': 'process',
    '道': 'way',
    '違反': 'violation',
    '遠い': 'far',
    '適合': 'conform',
    '避ける': 'avoid',
    '配列': 'array',
    '酷い': 'terrible',
    '重い': 'heavy',
    '長い': 'long',
    '閉める': 'close',
    '開ける': 'open',
    '間': 'between',
    '関係': 'relation',
    '関心': 'interest',
    '防御': 'defense',
    '除く': 'exclude',
    '際': 'occasion',
    '障壁': 'barrier',
    '難しい': 'difficult',
    '難易度': 'difficulty',
    '電源': 'power',
    '静か': 'quiet',
    '面': 'surface',
    '響く': 'resonate',
    '頂く': 'receive',
    '頻発': 'frequent',
    '類型': 'type',
    '飛ばす': 'skip',
    '高める': 'raise',
    '高度': 'advanced',

    # Final remaining batch
    'パーセンタイル': 'percentile',
    'ビルド': 'build',
    'ピクセル': 'pixel',
    'フォルダ': 'folder',
    'ブルーグリーン': 'blue-green',
    'ブローカー': 'broker',
    'プレイブック': 'playbook',
    'プール': 'pool',
    'ベロシティ': 'velocity',
    'ページネーション': 'pagination',
    'ボリューム': 'volume',
    'マジックナンバー': 'magic number',
    'メタタグ': 'meta tag',
    'メンター': 'mentor',
    'ランブック': 'runbook',
    'リネーム': 'rename',
    'リバート': 'revert',
    'リファインメント': 'refinement',
    'リージョン': 'region',
    'ロールフォワード': 'roll forward',
    '一時': 'temporary',
    '一方': 'on the other hand',
    '上手く': 'well',
    '不安定': 'unstable',
    '不足': 'shortage',
    '今後': 'from now on',
    '使い分け': 'use properly',
    '使える': 'usable',
    '傾向': 'tendency',
    '元': 'original',
    '全て': 'all',
    '具体': 'concrete',
    '内容': 'content',
    '再構築': 'rebuild',
    '分ける': 'separate',
    '切る': 'cut',
    '判定': 'judgment',
    '判明': 'become clear',
    '別': 'different',
    '動かない': 'not working',
    '可能性': 'possibility',
    '各': 'each',
    '同様': 'same',
    '向き': 'direction',
    '向け': 'for',
    '含める': 'include',
    '場面': 'scene',
    '変わる': 'change',
    '外': 'outside',
    '多く': 'many',
    '大変': 'very/difficult',
    '好み': 'preference',
    '始まり': 'beginning',
    '存在': 'exist',
    '完全': 'complete',
    '実': 'actual',
    '寄与': 'contribute',
    '少なく': 'few',
    '待ち時間': 'wait time',
    '得意': 'good at',
    '悪い': 'bad',
    '慎重': 'careful',
    '戻り値': 'return value',
    '手前': 'before',
    '振る舞い': 'behavior',
    '数': 'number',
    '新規': 'new',
    '日': 'day',
    '日々': 'daily',
    '日時': 'date and time',
    '早い': 'early',
    '早め': 'early',
    '明らか': 'clear',
    '書き換え': 'rewrite',
    '最も': 'most',
    '有る': 'exist',
    '本質': 'essence',
    '根': 'root',
    '欲しい': 'want',
    '求める': 'seek',
    '決まる': 'be decided',
    '活かす': 'make use of',
    '渡る': 'cross',
    '済む': 'finish',
    '減らす': 'reduce',
    '満たす': 'satisfy',
    '無い': 'not exist',
    '特徴': 'feature',
    '生じる': 'occur',
    '生む': 'produce',
    '目立つ': 'stand out',
    '相手': 'partner',
    '着く': 'arrive',
    '知識': 'knowledge',
    '確か': 'certain',
    '確認中': 'checking',
    '移る': 'move',
    '立てる': 'set up',
    '立つ': 'stand',
    '答える': 'answer',
    '経つ': 'pass',
    '続く': 'continue',
    '総': 'total',
    '考え': 'thought',
    '聞く': 'listen',
    '良し': 'good',
    '落ち着く': 'calm down',
    '見せる': 'show',
    '見出す': 'find out',
    '見積り': 'estimate',
    '触れる': 'touch',
    '言葉': 'word',
    '認める': 'recognize',
    '語る': 'tell',
    '読む': 'read',
    '越える': 'cross',
    '踏まえる': 'based on',
    '載る': 'be loaded',
    '近付く': 'approach',
    '述べる': 'state',
    '追加': 'add',
    '逆に': 'conversely',
    '通り': 'street/way',
    '進行中': 'in progress',
    '選ぶ': 'choose',
    '部分': 'part',
    '配る': 'distribute',
    '重ねる': 'stack',
    '間違い': 'mistake',
    '関わる': 'be involved',
    '関数': 'function',
    '限る': 'limit',
    '集まる': 'gather',
    '集める': 'collect',
    '頑張る': 'do one\'s best',
    '飛ぶ': 'fly',

    # Very last batch
    'レベル': 'level',
    'ロード': 'load',
    'ロードマップ': 'roadmap',
    '一対多': 'one-to-many',
    '一意': 'unique',
    '上部': 'upper',
    '並列': 'parallel',
    '主導権': 'initiative',
    '事前通知': 'advance notice',
    '二要素認証': '2FA',
    '代替案': 'alternative',
    '休み': 'break/day off',
    '会議': 'meeting',
    '依存性注入': 'DI',
    '侵害': 'breach',
    '保守可能': 'maintainable',
    '信頼できる': 'reliable',
    '先ほど述べたように': 'as mentioned',
    '全体会議': 'all-hands meeting',
    '共感': 'empathy',
    '共有する': 'share',
    '内部結合': 'inner join',
    '凝集度': 'cohesion',
    '処理': 'processing',
    '利益': 'benefit',
    '助け': 'help',
    '助ける': 'help',
    '動きますか': 'does it work?',
    '動きません': 'not working',
    '包括的': 'comprehensive',
    '協力する': 'cooperate',
    '単一責任': 'single responsibility',
    '参考までに': 'FYI',
    '取り除いて': 'remove',
    '古く': 'old',
    '合意': 'agreement',
    '合成': 'composition',
    '同意': 'agree',
    '名前空間': 'namespace',
    '問題なし': 'no problem',
    '回避策': 'workaround',
    '図': 'diagram',
    '在宅勤務': 'WFH',
    '境界条件': 'boundary condition',
    '壊れて': 'broken',
    '変更を依頼': 'request change',
    '多対多': 'many-to-many',
    '妥協': 'compromise',
    '学んだこと': 'lessons learned',
    '実際': 'actually',
    '尊重': 'respect',
    '左結合': 'left join',
    '巻き込み': 'involve',
    '弱み': 'weakness',
    '強み': 'strength',
    '復号化': 'decrypt',
    '必要になるまで': 'until needed',
    '忍耐': 'patience',
    '忙しい': 'busy',
    '意見': 'opinion',
    '成功する': 'succeed',
    '成功率': 'success rate',
    '成果物': 'deliverable',
    '戻る': 'return',
    '技術的負債': 'tech debt',
    '拡張可能': 'extensible',
    '持ち帰り': 'takeaway',
    '指摘': 'point out',
    '改善する': 'improve',
    '文書化': 'document',
    '文脈': 'context',
    '昇進': 'promotion',
    '明確にすると': 'to clarify',
    '明確化': 'clarify',
    '書いた': 'wrote',
    '最小化': 'minimize',
    '有効期限': 'expiration',
    '有給': 'paid leave',
    '期待される': 'expected',
    '欠点': 'drawback',
    '次に移る': 'move on',
    '正直': 'honestly',
    '決定論的': 'deterministic',
    '洞察': 'insight',
    '渡して': 'pass',
    '準備ができたら': 'when ready',
    '無効化': 'disable',
    '理由は': 'the reason is',
    '異議': 'objection',
    '発見': 'discovery',
    '私の意見では': 'IMO',
    '私の知る限り': 'AFAIK',
    '空いて': 'available',
    '立ち上がり': 'startup',
    '簡略化': 'simplify',
    '結合度': 'coupling',
    '結論として': 'in conclusion',
    '繰り返さない': 'don\'t repeat',
    '耐久性': 'durability',
    '背景情報': 'background info',
    '自動的': 'automatically',
    '要約すると': 'in summary',
    '見逃した場合': 'if you missed',
    '解決済み': 'resolved',
    '証明書': 'certificate',
    '詳しく': 'in detail',
    '説明させてください': 'let me explain',
    '読みやすい': 'readable',
    '読みやすく': 'readable',
    '責任がある': 'responsible',
    '軽微': 'minor',
    '辞退': 'decline',
    '返して': 'return',
    '返しますか': 'will you return?',
    '透明': 'transparent',
    '通過': 'pass through',
    '連絡を取れますか': 'can you reach?',
    '適応する': 'adapt',
    '選択肢': 'option',
    '重大': 'serious',
    '重複排除': 'dedup',
    '長所と短所': 'pros and cons',
    '関心の分離': 'separation of concerns',
    '閾値': 'threshold',
    '順次': 'sequentially',
    '順調': 'on track',
}


def get_translation(cloze: str) -> str:
    """Get English translation for a Japanese key word."""
    # Direct lookup
    if cloze in TRANSLATIONS:
        return TRANSLATIONS[cloze]

    # Try without trailing particles
    stripped = re.sub(r'[をにがはでとも]+$', '', cloze)
    if stripped in TRANSLATIONS:
        return TRANSLATIONS[stripped]

    # For compound words, try to match parts
    for jp, en in TRANSLATIONS.items():
        if jp in cloze and len(jp) > 2:
            return en

    # Return the original for unknown terms (likely English tech terms)
    return cloze


def process_csv(tier: int):
    """Add KeyMeaning column to a tier's CSV."""
    input_path = ROOT / f"tier{tier}-vocabulary.csv"
    output_path = ROOT / f"tier{tier}-vocabulary-new.csv"

    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # Add KeyMeaning to each row
    for row in rows:
        row['KeyMeaning'] = get_translation(row['Cloze'])

    # Write new CSV
    fieldnames = ['Sentence', 'Translation', 'Cloze', 'Pronunciation', 'Note', 'KeyMeaning']
    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Tier {tier}: {len(rows)} rows processed → {output_path.name}")
    return rows


def main():
    """Process all tier CSVs."""
    print("Adding KeyMeaning column to vocabulary CSVs\n")

    all_rows = []
    for tier in range(1, 7):
        rows = process_csv(tier)
        all_rows.extend(rows)

    # Report untranslated terms
    untranslated = set()
    for row in all_rows:
        if row['KeyMeaning'] == row['Cloze'] and not re.match(r'^[A-Za-z0-9\s\-\.]+$', row['Cloze']):
            untranslated.add(row['Cloze'])

    if untranslated:
        print(f"\n{len(untranslated)} terms need manual translation:")
        for term in sorted(untranslated)[:20]:
            print(f"  '{term}': '',")
        if len(untranslated) > 20:
            print(f"  ... and {len(untranslated) - 20} more")


if __name__ == '__main__':
    main()
