#!/usr/bin/env python3
"""
Migrate vocabulary categories to new taxonomy.
Transforms the Note field in all tier CSV files according to the new taxonomy structure.
"""

import csv
import os
from pathlib import Path
from collections import defaultdict

# Comprehensive mapping from old categories to new taxonomy
# Format: "Domain - Specific" with consistent separator " - "
CATEGORY_MAPPING = {
    # === TIER 1: Git, Status, Time, Basic Communication ===

    # Git Operations
    "Git - save changes": "Git - Commit",
    "Git - upload": "Git - Remote",
    "Git - download": "Git - Remote",
    "Git - combine": "Git - Merge",
    "Git - version line": "Git - Branch",
    "Git - clash": "Git - Conflict",
    "Git - replay commits": "Git - Rebase",
    "Git - switch branch": "Git - Branch",
    "Git - temporary save": "Git - Stash",
    "Git - difference": "Git - Diff",
    "Git - undo": "Git - Undo",
    "Git - select commit": "Git - Cherry-pick",
    "Git - combine commits": "Git - Squash",
    "Git - label version": "Git - Tag",
    "Git - copy repo": "Git - Clone",
    "Git - personal copy": "Git - Fork",
    "Git - show author": "Git - History",
    "Pull request": "Git - Collaboration",
    "Examine code": "Git - Collaboration",
    "Deploy to production": "DevOps - Release",
    "Software version": "Git - Version",
    "Version history": "Git - History",

    # Workflow Status
    "Status - completed": "Workflow - Completion",
    "Status - in progress": "Workflow - Progress",
    "Status - cannot proceed": "Workflow - Blocking",
    "Status report": "Workflow - Status",
    "Problem/bug": "Debug - Issue",
    "Repair/solve": "Debug - Fix",
    "Verify/confirm": "Workflow - Verification",
    "Prepared/complete": "Workflow - Completion",
    "Require": "Workflow - Requirement",
    "Assist": "Communication - Help",
    "Inquiry": "Communication - Question",

    # Communication - Basic
    "Gratitude": "Communication - Gratitude",
    "Agreement": "Communication - Agreement",
    "Understanding": "Communication - Acknowledgment",
    "Acknowledged": "Communication - Acknowledgment",
    "Certainly": "Communication - Agreement",
    "Apology": "Communication - Apology",
    "In fact": "Communication - Clarification",
    "Likely": "Communication - Uncertainty",
    "Perhaps": "Communication - Uncertainty",

    # Time Expressions
    "At present": "Time - Present",
    "Still/yet": "Time - Duration",
    "Already": "Time - Past",
    "Finished": "Workflow - Completion",
    "Soon": "Time - Future",
    "Later": "Time - Future",
    "Right now": "Time - Present",
    "By today": "Time - Deadline",
    "Recent": "Time - Past",
    "History": "Git - History",
    "Directly": "Workflow - Direct",
    "When ready": "Workflow - Status",

    # Development Actions
    "Test": "Testing - General",
    "Debug": "Debug - General",
    "Deploy": "DevOps - Deploy",
    "Execute": "Development - Execute",
    "Implement": "Development - Implement",
    "Refactor": "Code Quality - Refactoring",
    "Optimize": "Performance - Optimization",
    "Create": "Development - Create",
    "Delete": "Development - Delete",
    "Add": "Development - Add",
    "Remove": "Development - Remove",
    "Change": "Development - Modify",
    "Configure": "Development - Configure",
    "Dependencies": "Development - Dependencies",
    "Install": "Development - Install",
    "Import": "Development - Import",
    "Export": "Development - Export",
    "Call": "Development - Call",
    "Return": "Development - Return",
    "Pass": "Development - Pass",
    "Set": "Development - Configure",
    "Get/retrieve": "Development - Retrieve",
    "Fetch": "Development - Fetch",
    "Send": "Development - Send",
    "Receive": "Development - Receive",
    "Handle": "Development - Handle",
    "Handle/process": "Development - Handle",
    "Parse": "Development - Parse",
    "Validate": "Data - Validation",
    "Format": "Development - Format",

    # Bug/Error Related
    "Bug": "Debug - Bug",
    "Error": "Debug - Error",
    "Crash": "Debug - Crash",
    "Break": "Debug - Break",
    "Broken": "Debug - Broken",
    "Fail": "Debug - Failure",
    "Failed": "Debug - Failure",
    "Checking": "Workflow - Verification",
    "Pass": "Testing - Pass",
    "Success": "Workflow - Success",
    "Work": "Workflow - Status",
    "Doesn't work": "Debug - Issue",
    "Connection": "Infrastructure - Connection",
    "Authentication": "Security - Authentication",
    "Cause": "Debug - Root Cause",
    "Root cause": "Debug - Root Cause",
    "Simple": "Development - Simple",
    "Hotfix": "Debug - Hotfix",
    "Apply": "Development - Apply",
    "Workaround": "Debug - Workaround",
    "Temporary": "Development - Temporary",
    "Permanent": "Development - Permanent",
    "Regression": "Testing - Regression",
    "Flaky": "Testing - Flaky",
    "Reproduce": "Debug - Reproduce",
    "Steps": "Debug - Steps",
    "Expected": "Testing - Expected",
    "Actual": "Testing - Actual",
    "Investigate": "Debug - Investigate",
    "Troubleshoot": "Debug - Troubleshoot",
    "Readable": "Code Quality - Readability",

    # Code Structure
    "File": "Development - File",
    "Folder": "Development - Folder",
    "Function": "Development - Function",
    "Variable": "Development - Variable",
    "Constant": "Development - Constant",
    "String": "Data - Type",
    "Number": "Data - Type",
    "Boolean": "Data - Type",
    "Array": "Data - Type",
    "Object": "Data - Type",
    "Null": "Data - Type",
    "Undefined": "Data - Type",
    "Type": "Data - Type",
    "Class": "Development - Class",
    "Method": "Development - Method",
    "Parameter": "Development - Parameter",
    "Argument": "Development - Argument",
    "Callback": "Development - Callback",
    "Async": "Development - Async",
    "Await": "Development - Async",
    "Promise": "Development - Promise",
    "Loop": "Development - Loop",
    "Condition": "Development - Condition",
    "Top": "Development - Structure",
    "Default": "Development - Default",
    "Module": "Development - Module",
    "Package": "Development - Package",

    # === TIER 2: Agile, Testing, API, Database ===

    # Agile/Project Management
    "Daily meeting": "Agile - Meeting",
    "Development cycle": "Agile - Sprint",
    "Task queue": "Agile - Backlog",
    "Work item": "Agile - Task",
    "Work unit": "Agile - Task",
    "Feature description": "Agile - User Story",
    "Large feature": "Agile - Epic",
    "Importance level": "Agile - Priority",
    "Urgent": "Agile - Priority",
    "Not urgent": "Agile - Priority",
    "Critical obstacle": "Agile - Blocker",
    "Specification": "Agile - Specification",
    "Remove obstacle": "Agile - Blocker",
    "Dependency": "Agile - Dependency",
    "Due date": "Agile - Deadline",
    "Key achievement": "Agile - Milestone",
    "Project boundaries": "Agile - Scope",
    "Not included": "Agile - Scope",
    "Expanding requirements": "Agile - Scope",
    "Time prediction": "Agile - Estimation",
    "Effort measure": "Agile - Estimation",
    "Team speed": "Agile - Velocity",
    "Available resources": "Agile - Capacity",
    "Available time": "Agile - Capacity",
    "Interested party": "Agile - Stakeholder",
    "Project needs": "Agile - Requirement",
    "Output": "Agile - Deliverable",
    "Schedule": "Agile - Timeline",
    "Future plan": "Agile - Roadmap",
    "Start meeting": "Agile - Meeting",
    "Retrospective": "Agile - Meeting",
    "Task organization": "Agile - Planning",
    "Ticket preparation": "Agile - Grooming",
    "Backlog review": "Agile - Refinement",
    "Demonstration": "Agile - Demo",
    "Quick meeting": "Agile - Sync",
    "Private meeting": "Agile - Meeting",
    "Company meeting": "Agile - Meeting",
    "Not real-time": "Communication - Async",
    "Meeting": "Agile - Meeting",
    "Meeting topics": "Agile - Agenda",
    "Task assignment": "Agile - Assignment",
    "Responsible person": "Agile - Owner",
    "Assign": "Agile - Assignment",
    "Current state": "Workflow - Status",
    "Advancement": "Workflow - Progress",
    "On track": "Workflow - Status",
    "At risk": "Workflow - Risk",

    # API & HTTP
    "Application interface": "API - Concept",
    "API URL": "API - Endpoint",
    "API call": "API - Request",
    "API reply": "API - Response",
    "HTTP method": "HTTP - Method",
    "Request metadata": "HTTP - Header",
    "Request content": "HTTP - Body",
    "Data sent": "HTTP - Payload",
    "URL parameters": "HTTP - Query",
    "URL variable": "HTTP - Parameter",
    "HTTP response code": "HTTP - Status Code",
    "Success response": "HTTP - Status Code",
    "Created response": "HTTP - Status Code",
    "Client error": "HTTP - Status Code",
    "Auth error": "HTTP - Status Code",
    "Permission error": "HTTP - Status Code",
    "Not found error": "HTTP - Status Code",
    "Server error": "HTTP - Status Code",
    "Time limit exceeded": "HTTP - Timeout",
    "Try again": "HTTP - Retry",
    "Request limit": "HTTP - Rate Limit",
    "Slow down": "HTTP - Rate Limit",
    "API architecture": "API - Architecture",
    "Query language": "API - GraphQL",
    "Event notification": "API - Webhook",
    "Return URL": "API - Callback",
    "Identity verification": "Security - Authentication",
    "Permission check": "Security - Authorization",
    "Auth credential": "Security - Token",
    "Token format": "Security - JWT",
    "Auth protocol": "Security - OAuth",
    "Environment variable": "Infrastructure - Environment",
    "Sensitive data": "Security - Secret",
    "Auth info": "Security - Credentials",
    "Encryption": "Security - Encryption",
    "Secure HTTP": "Security - HTTPS",
    "Security credential": "Security - Certificate",
    "Cross-origin issue": "Security - CORS",
    "Request source": "Security - Origin",
    "Response delay": "Performance - Latency",
    "Data rate": "Performance - Throughput",
    "Network capacity": "Infrastructure - Bandwidth",
    "Domain system": "Infrastructure - DNS",
    "Network address": "Infrastructure - IP",
    "Network port": "Infrastructure - Port",
    "Network connection": "Infrastructure - WebSocket",

    # Database
    "Data storage": "Database - General",
    "Production": "Infrastructure - Production",
    "Database request": "Database - Query",
    "Database table": "Database - Table",
    "Table column": "Database - Column",
    "Table row": "Database - Row",
    "Insert": "Database - Insert",
    "Unique": "Database - Constraint",
    "Data structure": "Database - Schema",
    "Schema change": "Database - Migration",
    "Undo change": "Database - Rollback",
    "Initial data": "Database - Seed",
    "Search optimization": "Database - Index",
    "Primary key": "Database - Key",
    "Foreign key": "Database - Key",
    "Relationship": "Database - Relationship",
    "One-to-many": "Database - Relationship",
    "Many-to-many": "Database - Relationship",
    "Join": "Database - Join",
    "Left join": "Database - Join",
    "Inner join": "Database - Join",
    "SQL command": "Database - SQL",
    "SQL clause": "Database - SQL",
    "Atomic operation": "Database - Transaction",
    "Save changes": "Database - Commit",
    "Undo changes": "Database - Rollback",
    "Lock conflict": "Database - Deadlock",
    "Data lock": "Database - Lock",
    "DB connections": "Database - Connection Pool",
    "Copy database": "Database - Replica",
    "Main database": "Database - Primary",
    "Backup switch": "Database - Failover",
    "Data copy": "Database - Backup",
    "Data recovery": "Database - Restore",
    "Database type": "Database - Type",
    "Object mapper": "Database - ORM",
    "Data model": "Database - Model",
    "Data object": "Database - Entity",
    "Data access pattern": "Database - Repository",
    "Data organization": "Database - Normalization",
    "Data optimization": "Database - Denormalization",
    "Data distribution": "Database - Sharding",
    "Data split": "Database - Partition",

    # Testing
    "Verification": "Testing - General",
    "Component test": "Testing - Unit",
    "System test": "Testing - Integration",
    "End-to-end test": "Testing - E2E",
    "Test scenario": "Testing - Edge Case",
    "Test collection": "Testing - Suite",
    "Test check": "Testing - Assertion",
    "Test assertion": "Testing - Assertion",
    "Fake object": "Testing - Mock",
    "Fake implementation": "Testing - Stub",
    "Call tracker": "Testing - Spy",
    "Test data": "Testing - Fixture",
    "Test preparation": "Testing - Setup",
    "Test cleanup": "Testing - Teardown",
    "Code coverage": "Testing - Coverage",
    "Test success": "Testing - Pass",
    "Continuous integration": "DevOps - CI",
    "Test skip": "Testing - Skip",
    "Unreliable test": "Testing - Flaky",
    "Bug prevention test": "Testing - Regression",
    "Test-driven development": "Testing - TDD",
    "TDD cycle": "Testing - TDD",
    "Basic test": "Testing - Smoke",
    "Basic verification": "Testing - Sanity",
    "Normal flow": "Testing - Happy Path",
    "Boundary condition": "Testing - Boundary",
    "Error test": "Testing - Negative",
    "Performance test": "Testing - Performance",
    "Limit test": "Testing - Stress",
    "Speed test": "Testing - Performance",
    "Human testing": "Testing - Manual",
    "Quality assurance": "Testing - QA",
    "Test environment": "Infrastructure - Staging",
    "Live environment": "Infrastructure - Production",
    "System setup": "Infrastructure - Environment",
    "Build process": "DevOps - Pipeline",
    "Compilation": "DevOps - Build",
    "Build output": "DevOps - Artifact",
    "Troubleshooting mode": "Debug - Mode",
    "Detailed output": "Debug - Verbose",
    "UI test": "Testing - Snapshot",
    "Reference file": "Testing - Golden",
    "Consistent results": "Testing - Deterministic",
    "Independent": "Testing - Isolation",
    "Concurrent": "Testing - Parallel",
    "In order": "Testing - Sequential",
    "Automatically": "Testing - Automation",
    "Test summary": "Testing - Report",

    # === TIER 3: Architecture, Cloud, DevOps ===

    # Code Review
    "Approval": "Code Review - Approval",
    "Minor suggestion": "Code Review - Nit",
    "Minor issue": "Code Review - Minor",
    "Major issue": "Code Review - Major",
    "Security issue": "Code Review - Security",
    "Suggestion": "Code Review - Suggestion",
    "Question": "Communication - Question",
    "Concern": "Communication - Concern",
    "Alternative": "Code Review - Alternative",
    "Optional": "Code Review - Optional",
    "Required": "Code Review - Required",
    "Addressed": "Code Review - Addressed",
    "Resolved": "Code Review - Resolved",
    "Outdated": "Code Review - Outdated",
    "Stale": "Code Review - Stale",
    "Changes requested": "Code Review - Changes Requested",
    "Approved": "Code Review - Approved",
    "Merge": "Git - Merge",
    "Squash": "Git - Squash",
    "Rebase": "Git - Rebase",
    "Conflict": "Git - Conflict",
    "Diff": "Git - Diff",
    "Clean": "Code Quality - Clean",
    "Elegant": "Code Quality - Clean",
    "Hacky": "Code Quality - Technical Debt",
    "Magic number": "Code Quality - Anti-pattern",
    "Hardcoded": "Code Quality - Anti-pattern",
    "Duplication": "Code Quality - DRY",
    "Don't repeat yourself": "Code Quality - DRY",
    "DRY": "Code Quality - DRY",
    "Extract": "Code Quality - Refactoring",
    "Inline": "Code Quality - Refactoring",
    "Rename": "Code Quality - Refactoring",
    "Simplify": "Code Quality - Refactoring",
    "Clarify": "Communication - Clarification",
    "Document": "Code Quality - Documentation",
    "Comment": "Code Quality - Documentation",
    "TODO": "Code Quality - TODO",
    "FIXME": "Code Quality - FIXME",
    "Technical debt": "Code Quality - Technical Debt",
    "Tradeoff": "Architecture - Tradeoff",
    "Performance": "Performance - General",
    "Security": "Security - General",
    "Edge case": "Testing - Edge Case",
    "Null check": "Code Quality - Validation",
    "Error handling": "Code Quality - Error Handling",
    "Type safety": "Code Quality - Type Safety",
    "Best practice": "Code Quality - Best Practice",

    # Architecture
    "Architecture": "Architecture - General",
    "Design": "Architecture - Design",
    "Pattern": "Architecture - Pattern",
    "Component": "Architecture - Component",
    "Service": "Architecture - Service",
    "Controller": "Architecture - Layer",
    "Middleware": "Architecture - Middleware",
    "Layer": "Architecture - Layer",
    "Interface": "Architecture - Interface",
    "Abstraction": "Architecture - Abstraction",
    "Encapsulation": "Architecture - Encapsulation",
    "Inheritance": "Architecture - Inheritance",
    "Composition": "Architecture - Composition",
    "Dependency injection": "Architecture - DI",
    "Singleton": "Architecture - Pattern",
    "Factory": "Architecture - Pattern",
    "Observer": "Architecture - Pattern",
    "Model-View-Controller": "Architecture - MVC",
    "Microservices": "Architecture - Microservices",
    "Monolith": "Architecture - Monolith",
    "Modular": "Architecture - Modular",
    "Scalable": "Architecture - Scalability",
    "Maintainable": "Code Quality - Maintainability",
    "Extensible": "Architecture - Extensibility",
    "Reusable": "Architecture - Reusability",
    "Testable": "Architecture - Testability",
    "Loosely coupled": "Architecture - Coupling",
    "Tightly coupled": "Architecture - Coupling",
    "Cohesion": "Architecture - Cohesion",
    "Coupling": "Architecture - Coupling",
    "Separation of concerns": "Architecture - SoC",
    "Single responsibility": "Architecture - SOLID",
    "SOLID principles": "Architecture - SOLID",
    "KISS": "Code Quality - KISS",
    "YAGNI": "Code Quality - YAGNI",
    "Tech stack": "Architecture - Stack",
    "Framework": "Architecture - Framework",
    "Library": "Architecture - Library",
    "SDK": "Architecture - SDK",
    "API design": "API - Design",
    "Contract": "API - Contract",
    "Versioning": "API - Versioning",
    "Backward compatible": "API - Compatibility",
    "Breaking change": "API - Breaking Change",
    "Deprecate": "API - Deprecation",
    "Sunset": "API - Sunset",
    "Plan": "Workflow - Planning",
    "Legacy": "Architecture - Legacy",
    "Greenfield": "Architecture - Greenfield",

    # Cloud/Infrastructure
    "Server": "Infrastructure - Server",
    "Client": "Infrastructure - Client",
    "Container": "Cloud - Container",
    "Dockerfile": "Cloud - Docker",
    "Image": "Cloud - Docker",
    "Kubernetes": "Cloud - Kubernetes",
    "K8s": "Cloud - Kubernetes",
    "Pod": "Cloud - Kubernetes",
    "Node": "Cloud - Kubernetes",
    "Cluster": "Cloud - Kubernetes",
    "Deployment": "Cloud - Kubernetes",
    "Expose": "Cloud - Kubernetes",
    "Ingress": "Cloud - Kubernetes",
    "Namespace": "Cloud - Kubernetes",
    "ConfigMap": "Cloud - Kubernetes",
    "Secrets": "Cloud - Kubernetes",
    "Volume": "Cloud - Storage",
    "CI/CD": "DevOps - CI/CD",
    "Pipeline": "DevOps - Pipeline",
    "Trigger": "DevOps - Trigger",
    "Artifact": "DevOps - Artifact",
    "Release": "DevOps - Release",
    "Rollout": "DevOps - Rollout",
    "Rollback": "DevOps - Rollback",
    "Blue-green": "DevOps - Blue-Green",
    "Canary": "DevOps - Canary",
    "Feature flag": "DevOps - Feature Flag",
    "Load balancer": "Infrastructure - Load Balancer",
    "Auto-scaling": "Infrastructure - Auto-scaling",
    "Horizontal scaling": "Infrastructure - Scaling",
    "Vertical scaling": "Infrastructure - Scaling",
    "Instance": "Infrastructure - Instance",
    "Provisioning": "Infrastructure - Provisioning",
    "Infrastructure": "Infrastructure - General",
    "Terraform": "Infrastructure - IaC",
    "Resource": "Infrastructure - Resource",
    "CloudFormation": "AWS - CloudFormation",
    "Configuration": "Infrastructure - Configuration",
    "Env file": "Infrastructure - Environment",
    "Staging": "Infrastructure - Staging",
    "Development": "Infrastructure - Development",
    "Local": "Infrastructure - Local",
    "Remote": "Infrastructure - Remote",
    "SSH": "Infrastructure - SSH",
    "VPN": "Infrastructure - VPN",
    "Firewall": "Infrastructure - Firewall",
    "Security group": "AWS - Security Group",
    "VPC": "AWS - VPC",

    # AWS Services
    "AWS compute": "AWS - Compute",
    "AWS storage": "AWS - Storage",
    "AWS serverless": "AWS - Lambda",
    "AWS database": "AWS - RDS",
    "AWS NoSQL": "AWS - DynamoDB",
    "AWS cache": "AWS - ElastiCache",
    "AWS CDN": "AWS - CloudFront",
    "AWS DNS": "AWS - Route 53",
    "AWS API": "AWS - API Gateway",
    "AWS queue": "AWS - SQS",
    "AWS notifications": "AWS - SNS",
    "AWS containers": "AWS - ECS",
    "AWS Kubernetes": "AWS - EKS",
    "AWS serverless containers": "AWS - Fargate",
    "AWS identity": "AWS - IAM",
    "AWS policy": "AWS - IAM",
    "AWS role": "AWS - IAM",
    "AWS permission": "AWS - IAM",
    "AWS logging": "AWS - CloudWatch",
    "AWS alarm": "AWS - CloudWatch",
    "AWS metrics": "AWS - CloudWatch",
    "AWS log group": "AWS - CloudWatch",
    "AWS tracing": "AWS - X-Ray",
    "AWS load balancer": "AWS - ALB",
    "AWS network LB": "AWS - NLB",
    "AWS target group": "AWS - ALB",
    "AWS health check": "AWS - Health Check",
    "AWS availability zone": "AWS - Availability Zone",
    "AWS region": "AWS - Region",
    "AWS subnet": "AWS - VPC",
    "AWS NAT": "AWS - NAT Gateway",
    "AWS internet gateway": "AWS - Internet Gateway",
    "AWS block storage": "AWS - EBS",
    "AWS snapshot": "AWS - Snapshot",
    "AWS image": "AWS - AMI",
    "AWS secrets": "AWS - Secrets Manager",
    "AWS config": "AWS - Parameter Store",
    "AWS encryption": "AWS - KMS",
    "AWS auth": "AWS - Cognito",
    "AWS workflow": "AWS - Step Functions",
    "AWS events": "AWS - EventBridge",
    "AWS streaming": "AWS - Kinesis",
    "AWS data warehouse": "AWS - Redshift",
    "AWS query": "AWS - Athena",
    "AWS ETL": "AWS - Glue",
    "AWS build": "AWS - CodeBuild",
    "AWS deploy": "AWS - CodeDeploy",
    "AWS pipeline": "AWS - CodePipeline",
    "AWS audit": "AWS - CloudTrail",
    "AWS cost": "AWS - Cost Explorer",

    # Monitoring & Performance
    "Optimization": "Performance - Optimization",
    "Slow": "Performance - Latency",
    "Fast": "Performance - Optimization",
    "Latency": "Performance - Latency",
    "Response time": "Performance - Latency",
    "Throughput": "Performance - Throughput",
    "Bottleneck": "Performance - Bottleneck",
    "Profile": "Performance - Profiling",
    "Benchmark": "Performance - Benchmark",
    "Metric": "Monitoring - Metrics",
    "Dashboard": "Monitoring - Dashboard",
    "Alert": "Monitoring - Alert",
    "Threshold": "Monitoring - Threshold",
    "Monitor": "Monitoring - General",
    "Observability": "Monitoring - Observability",
    "Logging": "Monitoring - Logging",
    "Tracing": "Monitoring - Tracing",
    "Span": "Monitoring - Tracing",
    "Trace ID": "Monitoring - Tracing",
    "APM": "Monitoring - APM",
    "Datadog": "Monitoring - Datadog",
    "New Relic": "Monitoring - New Relic",
    "Splunk": "Monitoring - Splunk",
    "Grafana": "Monitoring - Grafana",
    "Prometheus": "Monitoring - Prometheus",
    "Health check": "Monitoring - Health Check",
    "Uptime": "Monitoring - Uptime",
    "Downtime": "Monitoring - Downtime",
    "SLA": "Monitoring - SLA",
    "SLO": "Monitoring - SLO",
    "SLI": "Monitoring - SLI",
    "Error rate": "Monitoring - Error Rate",
    "Success rate": "Monitoring - Success Rate",
    "P99": "Monitoring - Percentile",
    "Percentile": "Monitoring - Percentile",
    "Average": "Monitoring - Average",
    "Spike": "Monitoring - Traffic",
    "Incident": "Incident - General",
    "Outage": "Incident - Outage",
    "Postmortem": "Incident - Postmortem",
    "Root cause analysis": "Incident - RCA",
    "On-call": "Incident - On-call",
    "Paging": "Incident - Paging",
    "Escalation": "Incident - Escalation",
    "Runbook": "Incident - Runbook",
    "Playbook": "Incident - Playbook",
    "Remediate": "Incident - Remediation",
    "Mitigate": "Incident - Mitigation",
    "Recover": "Incident - Recovery",

    # === TIER 4: Security, Frontend, Data ===

    # Caching
    "Cache": "Performance - Caching",
    "Cache hit": "Performance - Caching",
    "Cache miss": "Performance - Caching",
    "Invalidate": "Performance - Caching",
    "Time to live": "Performance - Caching",
    "Expire": "Performance - Caching",
    "Evict": "Performance - Caching",
    "Redis": "Database - Redis",
    "Memcached": "Database - Memcached",
    "CDN": "Infrastructure - CDN",
    "Edge": "Infrastructure - Edge",
    "Warm up": "Performance - Caching",
    "Cold": "Performance - Caching",

    # Storage
    "Storage": "Infrastructure - Storage",
    "Blob": "Infrastructure - Storage",
    "Object storage": "Infrastructure - Storage",
    "File system": "Infrastructure - Storage",
    "Persistent": "Infrastructure - Storage",
    "Ephemeral": "Infrastructure - Storage",
    "Block storage": "Infrastructure - Storage",
    "IOPS": "Performance - IOPS",
    "Replication": "Database - Replication",
    "Consistency": "Database - Consistency",
    "Eventual consistency": "Database - Consistency",
    "Durability": "Infrastructure - Durability",
    "High availability": "Infrastructure - HA",
    "Redundancy": "Infrastructure - Redundancy",
    "Backup": "Infrastructure - Backup",
    "Restore": "Infrastructure - Restore",

    # Security
    "Vulnerability": "Security - Vulnerability",
    "Exploit": "Security - Vulnerability",
    "Attack": "Security - Attack",
    "Breach": "Security - Breach",
    "Encrypt": "Security - Encryption",
    "Decrypt": "Security - Encryption",
    "Hash": "Security - Hashing",
    "Salt": "Security - Hashing",
    "TLS": "Security - TLS",
    "HTTPS": "Security - HTTPS",
    "Certificate": "Security - Certificate",
    "Two-factor auth": "Security - 2FA",
    "Authorization": "Security - Authorization",
    "Access control": "Security - Access Control",
    "RBAC": "Security - RBAC",
    "Permission": "Security - Permission",
    "Least privilege": "Security - Least Privilege",
    "Credential": "Security - Credentials",
    "Token": "Security - Token",
    "Session": "Security - Session",
    "Cookie": "Security - Cookie",
    "XSS": "Security - XSS",
    "CSRF": "Security - CSRF",
    "Parameterized": "Security - Injection Prevention",
    "Injection": "Security - Injection",
    "Sanitize": "Security - Input Validation",
    "Whitelist": "Security - Whitelist",
    "Blacklist": "Security - Blacklist",
    "WAF": "Security - WAF",
    "DDoS": "Security - DDoS",
    "Rate limiting": "Security - Rate Limiting",
    "Throttle": "Security - Rate Limiting",
    "Audit": "Security - Audit",
    "Compliance": "Security - Compliance",
    "GDPR": "Security - Compliance",
    "PCI": "Security - Compliance",
    "SOC 2": "Security - Compliance",
    "Pen test": "Security - Pen Test",
    "Vulnerability scan": "Security - Scan",
    "Secret": "Security - Secret",
    "Key rotation": "Security - Key Rotation",
    "MFA": "Security - MFA",
    "SSO": "Security - SSO",
    "SAML": "Security - SAML",
    "OAuth": "Security - OAuth",

    # Frontend
    "Frontend": "Frontend - General",
    "Backend": "Backend - General",
    "Fullstack": "Development - Fullstack",
    "UI": "Frontend - UI",
    "UX": "Frontend - UX",
    "Props": "Frontend - React",
    "State": "Frontend - React",
    "Hook": "Frontend - React",
    "Render": "Frontend - Rendering",
    "Virtual DOM": "Frontend - React",
    "DOM": "Frontend - DOM",
    "Event": "Frontend - Event",
    "Listener": "Frontend - Event",
    "Handler": "Frontend - Event",
    "Binding": "Frontend - Binding",
    "Lifecycle": "Frontend - Lifecycle",
    "Mount": "Frontend - Lifecycle",
    "Unmount": "Frontend - Lifecycle",
    "SSR": "Frontend - SSR",
    "CSR": "Frontend - CSR",
    "Hydration": "Frontend - Hydration",
    "Lazy loading": "Frontend - Performance",
    "Code splitting": "Frontend - Performance",
    "Bundle": "Frontend - Build",
    "Minify": "Frontend - Build",
    "Transpile": "Frontend - Build",
    "webpack": "Frontend - Build",
    "Production build": "Frontend - Build",
    "Responsive": "Frontend - Responsive",
    "Breakpoint": "Frontend - Responsive",
    "CSS": "Frontend - CSS",
    "Flexbox": "Frontend - CSS",
    "Grid": "Frontend - CSS",
    "Animation": "Frontend - CSS",
    "Transition": "Frontend - CSS",
    "Accessibility": "Frontend - Accessibility",
    "a11y": "Frontend - Accessibility",
    "ARIA": "Frontend - Accessibility",
    "SEO": "Frontend - SEO",
    "Meta tag": "Frontend - SEO",
    "Viewport": "Frontend - Viewport",
    "Pixel": "Frontend - UI",
    "Form": "Frontend - Form",
    "Input field": "Frontend - Form",
    "Client-side": "Frontend - Client",
    "Submit": "Frontend - Form",
    "Modal": "Frontend - UI",
    "Toast": "Frontend - UI",
    "Notification": "Frontend - UI",
    "Development server": "Infrastructure - Development",

    # Backend
    "REST API": "API - REST",
    "Endpoint": "API - Endpoint",
    "Route": "Backend - Routing",
    "Router": "Backend - Routing",
    "Repository": "Backend - Repository",
    "Model": "Backend - Model",
    "Entity": "Backend - Entity",
    "DTO": "Backend - DTO",
    "Interceptor": "Backend - Interceptor",
    "Guard": "Backend - Guard",
    "Decorator": "Backend - Decorator",
    "Server-side": "Backend - Server",
    "Serialization": "Backend - Serialization",
    "Deserialize": "Backend - Serialization",
    "Prisma": "Database - ORM",
    "Query builder": "Database - Query Builder",
    "Raw SQL": "Database - SQL",
    "Pool": "Database - Connection Pool",
    "Connection pool": "Database - Connection Pool",
    "Transaction": "Database - Transaction",
    "Pessimistic locking": "Database - Lock",
    "Queue": "Backend - Queue",
    "Worker": "Backend - Worker",
    "Job": "Backend - Job",
    "Scheduler": "Backend - Scheduler",
    "Cron": "Backend - Cron",
    "Batch": "Backend - Batch",
    "Pagination": "Backend - Pagination",
    "Cursor": "Backend - Pagination",
    "Offset": "Backend - Pagination",
    "Limit": "Backend - Pagination",
    "Filter": "Backend - Query",
    "Sort": "Backend - Query",
    "Full-text search": "Backend - Search",
    "Search index": "Backend - Search",
    "Aggregate": "Backend - Aggregation",
    "Count": "Backend - Aggregation",
    "Sum": "Backend - Aggregation",
    "Webhook": "Backend - Webhook",
    "Publish": "Backend - Pub/Sub",
    "Subscribe": "Backend - Pub/Sub",
    "Message": "Backend - Messaging",
    "Broker": "Backend - Messaging",

    # Data Engineering
    "ETL": "Data - ETL",
    "Extract": "Data - ETL",
    "Transform": "Data - ETL",
    "Load": "Data - ETL",
    "Data pipeline": "Data - Pipeline",
    "Stream": "Data - Streaming",
    "Batch processing": "Data - Batch",
    "Real-time": "Data - Real-time",
    "Data warehouse": "Data - Warehouse",
    "Data lake": "Data - Lake",
    "Schema": "Data - Schema",
    "Parquet": "Data - Format",
    "CSV": "Data - Format",
    "JSON": "Data - Format",
    "XML": "Data - Format",
    "Normalize": "Data - Normalization",
    "Denormalize": "Data - Denormalization",
    "Dedup": "Data - Deduplication",
    "Data quality": "Data - Quality",
    "Clean": "Data - Cleansing",

    # === TIER 5: Communication, Soft Skills ===

    # Communication
    "Agree": "Communication - Agreement",
    "Disagree": "Communication - Disagreement",
    "Suggest": "Communication - Suggestion",
    "Recommend": "Communication - Recommendation",
    "Propose": "Communication - Proposal",
    "Opinion": "Communication - Opinion",
    "Thought": "Communication - Opinion",
    "Feedback": "Communication - Feedback",
    "Issue": "Communication - Issue",
    "Point": "Communication - Point",
    "Elaborate": "Communication - Elaboration",
    "Explain": "Communication - Explanation",
    "Example": "Communication - Example",
    "Context": "Communication - Context",
    "Background": "Communication - Background",
    "Summary": "Communication - Summary",
    "Recap": "Communication - Summary",
    "Conclusion": "Communication - Conclusion",
    "Decision": "Communication - Decision",
    "Consensus": "Communication - Consensus",
    "Alignment": "Communication - Alignment",
    "Compromise": "Communication - Compromise",
    "Option": "Communication - Options",
    "Pros and cons": "Communication - Analysis",
    "Advantage": "Communication - Analysis",
    "Disadvantage": "Communication - Analysis",
    "Benefit": "Communication - Analysis",
    "Risk": "Communication - Risk",
    "Impact": "Communication - Impact",
    "Scope": "Agile - Scope",
    "Priority": "Agile - Priority",
    "Critical": "Agile - Priority",
    "Blocker": "Agile - Blocker",
    "Nice to have": "Agile - Priority",
    "Must have": "Agile - Priority",
    "Requirement": "Agile - Requirement",
    "Assumption": "Communication - Assumption",
    "Constraint": "Communication - Constraint",
    "Limitation": "Communication - Limitation",
    "Timeline": "Agile - Timeline",
    "Deadline": "Agile - Deadline",
    "Milestone": "Agile - Milestone",
    "Deliverable": "Agile - Deliverable",

    # Workplace Acronyms
    "FYI": "Communication - FYI",
    "ASAP": "Communication - ASAP",
    "EOD": "Communication - EOD",
    "ETA": "Communication - ETA",
    "TBD": "Communication - TBD",
    "TL;DR": "Communication - Summary",
    "ICYMI": "Communication - FYI",
    "AFAIK": "Communication - Opinion",
    "IMO": "Communication - Opinion",
    "BTW": "Communication - FYI",

    # Workplace Communication
    "Ping": "Communication - Contact",
    "Loop in": "Communication - Contact",
    "Heads up": "Communication - Notice",
    "Follow up": "Communication - Follow-up",
    "Circle back": "Communication - Follow-up",
    "Touch base": "Communication - Sync",
    "Check in": "Communication - Sync",
    "Update": "Communication - Update",
    "Status": "Workflow - Status",
    "Progress": "Workflow - Progress",
    "Help": "Communication - Help",
    "Request": "Communication - Request",
    "Reminder": "Communication - Reminder",
    "Notice": "Communication - Notice",
    "Announcement": "Communication - Announcement",
    "Thread": "Communication - Thread",
    "Channel": "Communication - Channel",
    "DM": "Communication - DM",
    "Mention": "Communication - Mention",
    "Tag": "Communication - Tag",
    "React": "Communication - React",
    "Acknowledge": "Communication - Acknowledgment",
    "Confirm": "Communication - Confirmation",
    "Approve": "Communication - Approval",
    "Decline": "Communication - Decline",
    "Reschedule": "Communication - Schedule",
    "Cancel": "Communication - Cancel",
    "Postpone": "Communication - Schedule",
    "Available": "Communication - Availability",
    "Busy": "Communication - Availability",
    "OOO": "Communication - OOO",
    "PTO": "Communication - PTO",
    "WFH": "Communication - WFH",
    "Timezone": "Communication - Timezone",
    "Async": "Communication - Async",
    "Sync": "Communication - Sync",

    # === TIER 6: Presentations, Career ===

    # Presentations - Keep existing good structure
    "Presentation - agenda": "Presentation - Agenda",
    "Presentation - overview": "Presentation - Overview",
    "Presentation - introduction": "Presentation - Introduction",
    "Presentation - background": "Presentation - Background",
    "Presentation - context": "Presentation - Context",
    "Presentation - objective": "Presentation - Objective",
    "Presentation - goal": "Presentation - Goal",
    "Presentation - scope": "Presentation - Scope",
    "Presentation - timeline": "Presentation - Timeline",
    "Presentation - milestone": "Presentation - Milestone",
    "Presentation - progress": "Presentation - Progress",
    "Presentation - status": "Presentation - Status",
    "Presentation - demo": "Presentation - Demo",
    "Presentation - walkthrough": "Presentation - Walkthrough",
    "Presentation - screenshot": "Presentation - Visual",
    "Presentation - diagram": "Presentation - Visual",
    "Presentation - chart": "Presentation - Visual",
    "Presentation - graph": "Presentation - Visual",
    "Presentation - metric": "Presentation - Data",
    "Presentation - data": "Presentation - Data",
    "Presentation - result": "Presentation - Result",
    "Presentation - finding": "Presentation - Finding",
    "Presentation - insight": "Presentation - Insight",
    "Presentation - lesson learned": "Presentation - Lesson",
    "Presentation - takeaway": "Presentation - Takeaway",
    "Presentation - recommendation": "Presentation - Recommendation",
    "Presentation - next steps": "Presentation - Next Steps",
    "Presentation - action item": "Presentation - Action Item",
    "Presentation - question": "Presentation - Q&A",
    "Presentation - feedback": "Presentation - Q&A",
    "Presentation - concern": "Presentation - Q&A",
    "Presentation - comment": "Presentation - Q&A",
    "Presentation - clarification": "Presentation - Transition",
    "Presentation - example": "Presentation - Example",
    "Presentation - specifically": "Presentation - Transition",
    "Presentation - in other words": "Presentation - Transition",
    "Presentation - to summarize": "Presentation - Closing",
    "Presentation - in conclusion": "Presentation - Closing",
    "Presentation - moving on": "Presentation - Transition",
    "Presentation - going back": "Presentation - Transition",
    "Presentation - as I mentioned": "Presentation - Transition",
    "Presentation - to clarify": "Presentation - Transition",
    "Presentation - let me explain": "Presentation - Transition",
    "Presentation - the reason is": "Presentation - Explanation",
    "Presentation - this means": "Presentation - Explanation",
    "Presentation - the impact is": "Presentation - Impact",
    "Presentation - the benefit is": "Presentation - Benefit",
    "Presentation - the challenge is": "Presentation - Challenge",
    "Presentation - the solution is": "Presentation - Solution",
    "Presentation - thank you": "Presentation - Closing",

    # Career - Keep existing good structure
    "Career - team": "Career - Team",
    "Career - manager": "Career - Manager",
    "Career - lead": "Career - Lead",
    "Career - senior": "Career - Senior",
    "Career - junior": "Career - Junior",
    "Career - mentor": "Career - Mentor",
    "Career - mentee": "Career - Mentee",
    "Career - onboarding": "Career - Onboarding",
    "Career - ramp up": "Career - Onboarding",
    "Career - performance": "Career - Performance",
    "Career - review": "Career - Review",
    "Career - feedback": "Career - Feedback",
    "Career - growth": "Career - Growth",
    "Career - skill": "Career - Skill",
    "Career - strength": "Career - Strength",
    "Career - weakness": "Career - Weakness",
    "Career - goal": "Career - Goal",
    "Career - objective": "Career - Objective",
    "Career - OKR": "Career - OKR",
    "Career - KPI": "Career - KPI",
    "Career - promotion": "Career - Promotion",
    "Career - level": "Career - Level",
    "Career - title": "Career - Title",
    "Career - responsibility": "Career - Responsibility",
    "Career - ownership": "Career - Ownership",
    "Career - initiative": "Career - Initiative",
    "Career - proactive": "Career - Proactive",
    "Career - collaborate": "Career - Collaboration",
    "Career - communicate": "Career - Communication",
    "Career - document": "Career - Documentation",
    "Career - share": "Career - Knowledge Sharing",
    "Career - learn": "Career - Learning",
    "Career - improve": "Career - Improvement",
    "Career - adapt": "Career - Adaptability",
    "Career - flexible": "Career - Flexibility",
    "Career - reliable": "Career - Reliability",
    "Career - accountable": "Career - Accountability",
    "Career - transparent": "Career - Transparency",
    "Career - honest": "Career - Honesty",
    "Career - respect": "Career - Respect",
    "Career - inclusive": "Career - Inclusion",
    "Career - support": "Career - Support",
    "Career - help": "Career - Help",
    "Career - ask": "Career - Communication",
    "Career - listen": "Career - Listening",
    "Career - empathy": "Career - Empathy",
    "Career - patience": "Career - Patience",
    "Career - focus": "Career - Focus",
    "Career - balance": "Career - Balance",
    "Career - succeed": "Career - Success",

    # Additional mappings for unmapped categories
    "Discard": "Git - Undo",
    "Escape": "Security - Input Validation",
    "Important": "Agile - Priority",
    "Resolve": "Debug - Fix",
    "Fundamentally": "Communication - Explanation",
}


def migrate_category(old_category: str) -> str:
    """Map old category to new taxonomy."""
    # Direct mapping
    if old_category in CATEGORY_MAPPING:
        return CATEGORY_MAPPING[old_category]

    # Check if it's already in the new format (Domain - Specific)
    if " - " in old_category and old_category[0].isupper():
        # Normalize capitalization
        parts = old_category.split(" - ")
        return " - ".join(p.strip().title() for p in parts)

    # Fallback: create a category based on content
    # This catches any unmapped categories
    return f"Other - {old_category.title()}"


def process_csv(input_path: str, output_path: str, tier: int) -> dict:
    """Process a single CSV file and migrate categories."""
    stats = {
        "total": 0,
        "migrated": 0,
        "unchanged": 0,
        "categories_before": set(),
        "categories_after": set(),
    }

    rows = []
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames

        for row in reader:
            stats["total"] += 1
            old_category = row["Note"]
            stats["categories_before"].add(old_category)

            new_category = migrate_category(old_category)
            stats["categories_after"].add(new_category)

            if old_category != new_category:
                stats["migrated"] += 1
            else:
                stats["unchanged"] += 1

            row["Note"] = new_category
            rows.append(row)

    # Write output
    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    return stats


def main():
    """Run the migration on all tier files."""
    base_dir = Path(__file__).parent.parent

    print("=" * 60)
    print("VOCABULARY TAXONOMY MIGRATION")
    print("=" * 60)
    print()

    total_stats = {
        "total": 0,
        "migrated": 0,
        "all_categories_before": set(),
        "all_categories_after": set(),
    }

    for tier in range(1, 7):
        input_file = base_dir / f"tier{tier}-vocabulary.csv"
        output_file = input_file  # Overwrite in place

        if not input_file.exists():
            print(f"Warning: {input_file} not found, skipping...")
            continue

        print(f"\nProcessing Tier {tier}...")
        stats = process_csv(str(input_file), str(output_file), tier)

        total_stats["total"] += stats["total"]
        total_stats["migrated"] += stats["migrated"]
        total_stats["all_categories_before"].update(stats["categories_before"])
        total_stats["all_categories_after"].update(stats["categories_after"])

        print(f"  Sentences: {stats['total']}")
        print(f"  Categories migrated: {stats['migrated']}")
        print(f"  Categories unchanged: {stats['unchanged']}")
        print(f"  Unique categories before: {len(stats['categories_before'])}")
        print(f"  Unique categories after: {len(stats['categories_after'])}")

    print()
    print("=" * 60)
    print("MIGRATION SUMMARY")
    print("=" * 60)
    print(f"Total sentences processed: {total_stats['total']}")
    print(f"Total categories migrated: {total_stats['migrated']}")
    print(f"Unique categories before: {len(total_stats['all_categories_before'])}")
    print(f"Unique categories after: {len(total_stats['all_categories_after'])}")
    print(f"Category reduction: {len(total_stats['all_categories_before']) - len(total_stats['all_categories_after'])} fewer categories")

    # Show domain distribution
    print()
    print("DOMAIN DISTRIBUTION:")
    print("-" * 40)
    domain_counts = defaultdict(int)
    for cat in total_stats["all_categories_after"]:
        if " - " in cat:
            domain = cat.split(" - ")[0]
            domain_counts[domain] += 1
        else:
            domain_counts["Other"] += 1

    for domain, count in sorted(domain_counts.items(), key=lambda x: -x[1]):
        print(f"  {domain}: {count} categories")

    print()
    print("Migration complete!")


if __name__ == "__main__":
    main()
